const Map<String, String> stArabic = {
  'hint_enter_email': 'عنوان البريد الإلكتروني',
  'hint_password': 'كلمة المرور',
  'hint_old_password': 'كلمة المرورالسابقة',
  'hint_new_password': 'كلمة المرور الجديدة',
  'hint_confirm_password': 'تأكيد كلمة المرور',
  'hint_full_name': 'الاسم الكامل*',
  'hint_dob': 'تاريخ الميلاد*',
  'hint_phone_number': 'رقم الهاتف*',
  'hint_country_selection': 'تحديد الدولة*',
  'hint_traveling_from': 'البلد المسافر منها؟',
  'hint_traveling_to': 'البلد المسافر إليها؟',
  'lbl_forgot_password': 'هل نسيت كلمة السر؟',
  'lbl_forgot_password_title': 'هل نسيت كلمة السر',
  'lbl_delete_account': 'کھاتہ مٹا دو',
  'lbl_change_password': 'تغيير كلمة المرور',
  'lbl_dont_have_account': 'هل ليس لديك حساب؟  ',
  'lbl_already_have_account': 'هل لديك حساب بالفعل؟ ',
  'lbl_accept_term': 'قبول الشروط والأحكام',
  'lbl_sign_up': 'حساب جديد',
  'lbl_sign_in': 'تسجيل الدخول',
  'lbl_login': 'تسجيل الدخول',
  'lbl_logout': 'تسجيل الخروج',
  'lbl_ok': 'حسنًا',
  'lbl_submit': 'تقديم',
  'lbl_save': 'حفظ',
  'lbl_verify_email': 'التحقق من البريد الإلكتروني',
  'lbl_reset_password': 'إعادة تعيين كلمة المرور',
  'lbl_home': 'الصفحة الرئيسية',
  'lbl_my_profile': 'الملف الشخصي',
  'lbl_language_selection': 'تحديد اللغة',
  'lbl_notification': 'إشعارات',
  'lbl_are_you_vaccinated': 'هل تلقيت اللقاح؟',
  'lbl_search_details': 'تفاصيل البحث',
  'lbl_travel_rules_from': 'قواعد السفر من',
  'lbl_to': 'إلى',
  'lbl_required_test': 'يتطلب فحص',
  'lbl_test_time': 'وقت الفحص',
  'lbl_age_reqiured_test': 'الحد الأدنى للعمر المطلوب لإجراء الفحص',
  'lbl_quarantine_required': 'يتطلب حجر صحي',
  'lbl_additional_doc_required': 'المستندات الإضافية المطلوبة',
  'lbl_link_submit_doc': 'رابط لتقديم المستند',
  'lbl_more_info_about_result': 'معلومات إضافية عن متطلبات الدخول',
  'lbl_test_required_for_country': 'الفحص مطلوب لـ',
  'lbl_session_expired': 'انتهت صلاحية الجلسة',
  'lbl_logout_msg': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
  'lbl_cancel': 'إلغاء',
  'lbl_yes': 'نعم',
  'lbl_no': 'لا',
  'lbl_days': 'أيام',
  'lbl_day': 'يوم',
  'lbl_year': 'عام',
  'lbl_years': 'أعوام',
  'lbl_session_expired_msg': 'انتهت الجلسة بسبب تسجيل الدخول على جهاز آخر.',
  'lbl_within_last': 'في خلال ---- الماضية',
  'lbl_hours_of_departure': 'ساعات المغادرة',
  'lbl_pfl_required': 'مطلوب معلومات الركاب المسبقة',
  'lbl_pfl_not_required': 'معلومات الركاب المسبقة غير مطلوبة',
  'lbl_before_arrival_in': 'قبل الوصول',
  'lbl_on_arrival_in': 'عند الوصول',
  'lbl_select_image': 'اختر صورة',
  'lbl_camera': 'الة تصوير',
  'lbl_gallery': 'صالة عرض',
  'lbl_update_app': 'تحديث التطبيق',
  'lbl_not_now': 'ليس الآن',
  'msg_something_went_wrong': 'هناك خطأ ما.',
  'msg_new_update': 'التحديث الجديد متاح الآن.',
  'msg_force_update': 'تحتاج إلى تحديث التطبيق',
  'msg_check_connection': 'تحقق من اتصالك بالإنترنت.',
  'msg_enter_full_name': 'يرجى إدخال الاسم الكامل',
  'msg_name_length': 'يجب ألا يزيد الاسم عن 70 حرفًا',
  'msg_enter_email': 'يرجى إدخال البريد الإلكتروني',
  'msg_enter_valid_email': 'يرجى إدخال عنوان بريد إلكتروني صحيح',
  'msg_enter_phone_number': 'يرجى إدخال رقم الهاتف',
  'msg_enter_valid_phone_number': 'يرجى إدخال رقم هاتف صحيح',
  'msg_phone_number_limit': 'مطلوب 8 أرقام كحد أدنى',
  'msg_phone_number_max_limit': 'الحد الأقصى المطلوب هو 15 رقمًا',
  'msg_enter_password': 'يرجى إدخال كلمة المرور',
  'msg_enter_old_password': 'يرجى إدخال كلمة المرور القديمة',
  'msg_enter_new_password': 'يرجى إدخال كلمة المرور الجديدة',
  'msg_enter_confirm_password': 'يرجى تأكيد كلمة المرور',
  'msg_password_limit': 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
  'msg_password_max_limit': 'يجب ألا تزيد كلمة المرور عن 15 حرفًا',
  'msg_new_password_limit':
      'يجب أن تتكون كلمة المرور الجديدة من 8 أحرف على الأقل',
  'msg_confirm_password_limit': 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
  'msg_password_not_match':
      'يجب أن تكون كلمة المرور وتأكيد كلمة المرور متطابقتين',
  'msg_new_password_not_match':
      'يجب أن تكون كلمة المرور الجديدة وتأكيد كلمة المرور متطابقتين',
  'msg_country_select': 'يرجى تحديد الدولة',
  'msg_select_profile_photo': 'يرجى تحديد صورة الملف الشخصي',
  'msg_enter_traveling_from': 'يرجى إدخال السفر من',
  'msg_enter_traveling_to': 'يرجى إدخال السفر إلى',
  'msg_same_country': 'السفر من البلدان والسفر إليها لا يمكن أن يكونا متشابهين',
  'msg_no_data_found': 'لا توجد معلومات',
  'msg_accept_terms_condition': 'الرجاء قبول الشروط والأحكام',
  'msg_select_dob': 'حدد تاريخ الميلاد',
  'msg_select_country': 'حدد الدولة',
  'lbl_alert': 'إنذار',
  'lbl_more_information': 'هذا البلد لديه معلومات سفر أكثر',
  'lbl_click_here': 'انقر هنا',
  'lbl_none': 'لا أحد',
  'lbl_not_required': 'غير مطلوب',
  'lbl_home_content':
      'أخذك للقاح الكامل يعني أنك تلقيت الجرعة الكاملة من اللقاح المعتمد.\n\n'
          'على سبيل المثال جرعتين من لقاح فايزر بيونتيك، وجرعتين من لقاح موديرنا، جرع واحدة من لقاح يانسن.\n'
          'يتم اعتبارك ملقحاً بالكامل بعد أسبوعين من أخذك للجرعة النهائية. إذا تم تلقيحك جزئياً أو كنت مسافر قبل مرور أسبوعين من أخذ جرعتك النهائية، حينها يتم اعتبارك غير ملقحاً.',
  'lbl_share_app': 'مشاركة ملف Berbe',
  'lbl_share': 'يشارك',
  'lbl_share_content':
      'انظر إلى أحدث قواعد السفر من دولة إلى أخرى مع Berbe. إنه سريع وبسيط ودقيق ومجاني بالكامل. احصل عليها عبر https://berbe.net berbe، نجعل السفر عملية سهلة!',
  'lbl_accept': 'Accept ',
  'lbl_terms_condition': 'Terms & Conditions',
  'msg_verify_email':
      'We have sent an activation link to your email. Please activate your account to Sign in. If you do not receive a confirmation email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
  'msg_reset_password':
      'We have sent an reset password link to your email. If you do not receive an email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
};
