const Map<String, String> stChinese = {
  'hint_enter_email': '电子邮箱地址',
  'hint_password': '密码',
  'hint_old_password': '旧密码',
  'hint_new_password': '新密码',
  'hint_confirm_password': '确认密码',
  'hint_full_name': '全名*',
  'hint_dob': '出生日期*',
  'hint_phone_number': '电话号码*',
  'hint_country_selection': '国家选择*',
  'hint_traveling_from': '从哪一个国家出发？',
  'hint_traveling_to': '目的地国家？',
  'lbl_forgot_password': '忘記密碼？',
  'lbl_forgot_password_title': '忘記密碼',
  'lbl_change_password': '更改密码',
  'lbl_delete_account': 'アカウントを削除する',
  'lbl_dont_have_account': '还没有账户？ ',
  'lbl_already_have_account': '已经有账户了？ ',
  'lbl_accept_term': '接受条款和条件',
  'lbl_sign_up': '注册',
  'lbl_sign_in': '登入',
  'lbl_login': '登录',
  'lbl_logout': '登出',
  'lbl_ok': '好的',
  'lbl_submit': '提交',
  'lbl_save': '保存',
  'lbl_verify_email': '验证电子邮箱',
  'lbl_reset_password': '重設密碼',
  'lbl_home': '首页',
  'lbl_my_profile': '我的个人资料',
  'lbl_language_selection': '语言选择',
  'lbl_notification': '通知',
  'lbl_are_you_vaccinated': '您是否已接种疫苗？',
  'lbl_search_details': '搜索详情',
  'lbl_travel_rules_from': '旅行限制从',
  'lbl_to': '至',
  'lbl_required_test': '需要检测',
  'lbl_test_time': '检测时间',
  'lbl_age_reqiured_test': '需要检测的最低年龄',
  'lbl_quarantine_required': '需要隔离',
  'lbl_additional_doc_required': '其他必需文件',
  'lbl_link_submit_doc': '提交文件的链接',
  'lbl_more_info_about_result': '关于入境要求的更多信息',
  'lbl_test_required_for_country': '需要检测',
  'lbl_session_expired': '会话已过期',
  'lbl_logout_msg': '您确定要登出吗？',
  'lbl_cancel': '取消',
  'lbl_yes': '是的',
  'lbl_no': '不是',
  'lbl_days': '天',
  'lbl_day': '天',
  'lbl_year': '年',
  'lbl_years': '年',
  'lbl_session_expired_msg': '由于在其他设备上登录，会话已过期。',
  'lbl_within_last': '在最近',
  'lbl_hours_of_departure': '小时内出发',
  'lbl_pfl_required': '需要提前提供乘客信息',
  'lbl_pfl_not_required': '不需要提前提供乘客信息',
  'lbl_before_arrival_in': '抵达 前',
  'lbl_on_arrival_in': '抵达 时',
  'lbl_select_image': '选择图片',
  'lbl_camera': '相机',
  'lbl_gallery': '画廊',
  'lbl_update_app': '更新应用',
  'lbl_not_now': '现在不要',
  'msg_something_went_wrong': '发生了错误。',
  'msg_new_update': '新的更新现在可用。',
  'msg_force_update': '需要强制更新应用程序',
  'msg_check_connection': '请检查您的网络连接。',
  'msg_enter_full_name': '请输入全名',
  'msg_name_length': '姓名不应超过70个字符',
  'msg_enter_email': '请输入电子邮箱',
  'msg_enter_valid_email': '请输入有效电子邮箱',
  'msg_enter_phone_number': '请输入电话号码',
  'msg_enter_valid_phone_number': '请输入有效电话号码',
  'msg_phone_number_limit': '最少需要8位数字',
  'msg_phone_number_max_limit': '最多需要15位数字',
  'msg_enter_password': '请输入密码',
  'msg_enter_old_password': '请输入旧密码',
  'msg_enter_new_password': '请输入新密码',
  'msg_enter_confirm_password': '请输入确认密码',
  'msg_password_limit': '密码必须至少有8个字符',
  'msg_password_max_limit': '密码最多为15个字符',
  'msg_new_password_limit': '新密码必须至少有8个字符',
  'msg_confirm_password_limit': '确认密码必须至少有8个字符',
  'msg_password_not_match': '密码和确认密码必须相同',
  'msg_new_password_not_match': '新密码和确认密码必须是相同的',
  'msg_country_select': '请选择国家',
  'msg_select_profile_photo': '请选择个人资料照片',
  'msg_enter_traveling_from': '请输入旅行出发地',
  'msg_enter_traveling_to': '请输入旅行目的地',
  'msg_same_country': '從國家旅行和前往國家旅行不能相同',
  'msg_no_data_found': '找不到数据',
  'msg_accept_terms_condition': '请接受条款和条件',
  'msg_select_dob': '選擇出生日期',
  'msg_select_country': '選擇國家',
  'lbl_alert': '警報',
  'lbl_more_information': '這個國家有更多的旅遊信息',
  'lbl_click_here': '點擊這裡',
  'lbl_none': '沒有',
  'lbl_not_required': '不需要',
  'lbl_home_content': '全剂量接种是指你已接种某个已获批准的疫苗的所有建议剂量。'
      '\n\n举个例子，辉瑞-生物科技 = 两剂，莫德纳 = 两剂，杨森 = 一剂'
      '\n接种最后一剂两周后意味着你已经完全接种了疫苗。如果你未完成全剂量疫苗接种，或距离你的最后一剂未到两周，你被视为未接种疫苗。',
  'lbl_share_app': '分享 Berbe',
  'lbl_share': '分享',
  'lbl_share_content':
      '使用Berbe查看各国旅行规定。它快速、易用、准确和完全免费。请在https://berbe.net获取它 Berbe，让旅行变得更轻松！',
  'lbl_accept': 'Accept ',
  'lbl_terms_condition': 'Terms & Conditions',
  'msg_verify_email':
      'We have sent an activation link to your email. Please activate your account to Sign in. If you do not receive a confirmation email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
  'msg_reset_password':
      'We have sent an reset password link to your email. If you do not receive an email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
};
