const Map<String, String> stEnglish = {
  'hint_enter_email': 'Email Id*',
  'hint_password': 'Password',
  'hint_old_password': 'Old Password',
  'hint_new_password': 'New Password',
  'hint_confirm_password': 'Confirm Password',
  'hint_full_name': 'Full Name*',
  'hint_dob': 'Date of Birth*',
  'hint_phone_number': 'Phone number*',
  'hint_country_selection': 'Country Selection*',
  'hint_traveling_from': 'Country Traveling From',
  'hint_traveling_to': 'Country Traveling To',
  'lbl_forgot_password': 'Forgot password?',
  'lbl_forgot_password_title': 'Forgot Password',
  'lbl_change_password': 'Change Password',
  'lbl_delete_account': 'Delete Account',
  'lbl_dont_have_account': 'Don\'t have account? ',
  'lbl_already_have_account': 'Already have an account? ',
  'lbl_accept_term': 'Accept Terms & Conditions',
  'lbl_sign_up': 'Sign Up',
  'lbl_sign_in': 'Sign In',
  'lbl_login': 'Log in',
  'lbl_logout': 'Logout',
  'lbl_ok': 'OK',
  'lbl_submit': 'Submit',
  'lbl_save': 'Save',
  'lbl_resend': 'Resend',
  'lbl_Delete': 'Yes, Delete',
  'lbl_verify_email': 'Verify Email',
  'lbl_congratulations': 'Congratulations!',
  'lbl_reset_password': 'Reset Password',
  'lbl_home': 'Home',
  'lbl_my_profile': 'My Profile',
  'lbl_language_selection': 'Language Selection',
  'lbl_notification': 'Notification',
  'lbl_are_you_vaccinated': 'Are You Vaccinated?',
  'lbl_search_details': 'Search Details',
  'lbl_travel_rules_from': 'Travel Rules From',
  'lbl_to': 'to',
  'lbl_required_test': 'Required Test',
  'lbl_test_time': 'Test Time',
  'lbl_age_reqiured_test': 'Minimum Age Required For Test',
  'lbl_quarantine_required': 'Quarantine Required',
  'lbl_additional_doc_required': 'Additional document(s) required',
  'lbl_link_submit_doc': 'Link to submit document',
   
  'lbl_more_info_about_result': 'More Information about entry requirement',
  'lbl_test_required_for_country': 'Test Required For',
  'lbl_session_expired': 'Session Expired',
  'lbl_logout_msg': 'Are you sure you want to logout?',
  'lbl_cancel': 'Cancel',
  'lbl_yes': 'Yes',
  'lbl_no': 'No',
  'lbl_days': 'Days',
  'lbl_day': 'Day',
  'lbl_year': 'Year',
  'lbl_years': 'Years',
  'lbl_session_expired_msg':
      'Session was expired due to logged in other device.',
  'lbl_within_last': 'Within last',
  'lbl_hours_of_departure': 'Hours of departure',
  'lbl_pfl_required': 'Advance Passenger Information is required',
  'lbl_pfl_not_required': 'Advance Passenger Information is not required',
  'lbl_before_arrival_in': 'Before arrival in',
  'lbl_on_arrival_in': 'On arrival in',
  'lbl_select_image': 'Select Image',
  'lbl_camera': 'Camera',
  'lbl_gallery': 'Gallery',
  'lbl_update_app': 'Update App',
  'lbl_not_now': 'Not Now',
  'msg_something_went_wrong': 'Something went wrong.',
  'msg_new_update': 'New update is available now.',
  'msg_force_update': 'Need to update app forcefully',
  'msg_check_connection': 'Check your internet connection.',
  'msg_enter_full_name': 'Please enter full name',
  'msg_name_length': 'Name should not be more then 70 characters',
  'msg_enter_email': 'Please enter email',
  'msg_enter_valid_email': 'Please enter a valid email',
  'msg_enter_phone_number': 'Please enter phone number',
  'msg_enter_valid_phone_number': 'Please enter valid phone number',
  'msg_phone_number_limit': 'Minimum 8 digits are required',
  'msg_phone_number_max_limit': 'Maximum 15 digits are required',
  'msg_enter_password': 'Please enter password',
  'msg_enter_old_password': 'Please enter old password',
  'msg_enter_new_password': 'Please enter new password',
  'msg_enter_confirm_password': 'Please enter confirm password',
  'msg_password_limit': 'Password must have at least 8 characters',
  'msg_password_max_limit': 'Password should be of maximum 15 characters',
  'msg_new_password_limit': 'New password must have at least 8 characters',
  'msg_confirm_password_limit':
      'Confirm password must have at least 8 characters',
  'msg_password_not_match': 'Password and confirm password must be same',
  'msg_new_password_not_match':
      'New password and confirm password must be same',
  'msg_country_select': 'Please select country',
  'msg_select_profile_photo': 'Please select profile photo',
  'msg_enter_traveling_from': 'Please enter traveling from',
  'msg_enter_traveling_to': 'Please enter traveling to',
  'msg_same_country':
      'Travelling From and Travelling To countries can\'t be same',
  'msg_no_data_found': 'No Data Found',
  'msg_accept_terms_condition': 'Please accept terms and conditions.',
  'msg_select_dob': 'Select date of birth',
  'msg_select_country': 'Please select country',
  'lbl_alert': 'ALERT',
  'lbl_more_information': 'This country has more travel information',
  'lbl_click_here': 'CLICK HERE',
  'lbl_none': 'None',
  'lbl_not_required': 'Not Required',
  'lbl_home_content':
      'Fully vaccinated means you have received the full dose of an approved vaccine.'
          '\n\nExample:'
          '\nPfizer BioNTech = 2 doses, Moderna = 2 doses, Janssen = 1 dose.'
          '\n\nYou are considered Fully Vaccinated 2 weeks after your final dose. If you have been partially vaccinated or are traveling within 2 weeks of your final dose, you are considered Unvaccinated.',
  'lbl_share_app': 'Share Berbe',
  'lbl_share': 'Share',
  'lbl_share_content':
      'Check out the latest travel rules from country to country with Berbe. It\'s fast, simple, accurate and completely free. Get it at https://berbe.net Berbe, making travel simple!',
  'lbl_accept': 'Accept ',
  'lbl_terms_condition': 'Terms & Conditions',
  'msg_verify_email':
      'We have sent an activation link to your email. Please activate your account to Sign in. If you do not receive a confirmation email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
  'msg_reset_password':
      'We have sent an reset password link to your email. If you do not receive an email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
  'lbl_or_continue_with': 'or continue with',
};
