const Map<String, String> stFrench = {
  'hint_enter_email': 'Adresse e-mail',
  'hint_password': 'Mot de passe',
  'hint_old_password': 'Ancien mot de passe',
  'hint_new_password': 'Nouveau mot de passe',
  'hint_confirm_password': 'Mot de passe de confirmation',
  'hint_full_name': 'Nom et prénom*',
  'hint_dob': 'Date de naissance*',
  'hint_phone_number': 'Numéro de téléphone*',
  'hint_country_selection': 'Sélection du pays*',
  'hint_traveling_from': 'Le pays de départ du voyage ?',
  'hint_traveling_to': 'Le pays de destination du voyage ?',
  'lbl_forgot_password': 'Mot de passe oublié?',
  'lbl_forgot_password_title': 'Mot de passe oublié',
  'lbl_change_password': 'Modifier le mot de passe',
  'lbl_delete_account': 'Supprimer le compte',
  'lbl_dont_have_account': 'Vous n\'avez pas de compte ? ',
  'lbl_already_have_account': 'Vous avez déjà un compte ? ',
  'lbl_accept_term': 'Accepter les conditions générales',
  'lbl_sign_up': 'S\'inscrire',
  'lbl_sign_in': 'S\'inscrire',
  'lbl_login': 'Se connecter',
  'lbl_logout': 'Se déconnecter',
  'lbl_ok': 'Ok',
  'lbl_submit': 'Envoyer',
  'lbl_save': 'Enregistrer',
  'lbl_verify_email': 'Vérifier votre e-mail',
  'lbl_reset_password': 'réinitialiser le mot de passe',
  'lbl_home': 'Accueil',
  'lbl_my_profile': 'Mon profil',
  'lbl_language_selection': 'Sélection de la langue',
  'lbl_notification': 'Notification',
  'lbl_are_you_vaccinated': 'Êtes-vous vacciné ?',
  'lbl_search_details': 'Résultats de la recherche',
  'lbl_travel_rules_from': 'Règles pour les voyages de',
  'lbl_to': 'vers',
  'lbl_required_test': 'Test requis',
  'lbl_test_time': 'Date du test',
  'lbl_age_reqiured_test': 'Âge minimum requis pour le test',
  'lbl_quarantine_required': 'Quarantaine requise',
  'lbl_additional_doc_required': 'Document(s) supplémentaire(s) requis',
  'lbl_link_submit_doc': 'Lien pour envoyer un document',
  'lbl_more_info_about_result':
      'Plus d\'informations sur les conditions d\'entrée',
  'lbl_test_required_for_country': 'Test requis pour',
  'lbl_session_expired': 'La session a expiré',
  'lbl_logout_msg': 'Êtes-vous sûr de vouloir vous déconnecter ?',
  'lbl_cancel': 'Annuler',
  'lbl_yes': 'Oui',
  'lbl_no': 'Non',
  'lbl_days': 'jours',
  'lbl_day': 'jour',
  'lbl_year': 'an',
  'lbl_years': 'ans',
  'lbl_session_expired_msg':
      'La session a expiré car vous êtes connecté sur un autre appareil.',
  'lbl_within_last': 'Au cours des',
  'lbl_hours_of_departure': 'heures avant le départ',
  'lbl_pfl_required': 'Informations préalables sur les voyageurs requises',
  'lbl_pfl_not_required':
      'Informations préalables sur les voyageurs non requises',
  'lbl_before_arrival_in': 'Avant l\'arrivée à',
  'lbl_on_arrival_in': 'À l\'arrivée à',
  'lbl_select_image': 'Sélectionner une image',
  'lbl_camera': 'Caméra',
  'lbl_gallery': 'Galerie',
  'lbl_update_app': 'Mettre à jour l\'application',
  'lbl_not_now': 'Pas maintenant',
  'msg_something_went_wrong': 'Une erreur s\'est produite.',
  'msg_new_update': 'Nouvelle mise à jour disponible.',
  'msg_force_update': 'L\'app a besoin d\'être mise à jour de force',
  'msg_check_connection': 'Vérifiez votre connexion internet.',
  'msg_enter_full_name': 'Saisissez vos nom et prénom',
  'msg_name_length': 'Le nom ne doit pas contenir plus de 70 caractères.',
  'msg_enter_email': 'Saisissez votre adresse e-mail',
  'msg_enter_valid_email': 'Saisissez une adresse e-mail valide',
  'msg_enter_phone_number': 'Saisissez un numéro de téléphone',
  'msg_enter_valid_phone_number': 'PSaisissez un numéro de téléphone valide',
  'msg_phone_number_limit': '8 chiffres minimum requis',
  'msg_phone_number_max_limit': '15 chiffres maximum requis',
  'msg_enter_password': 'Saisissez votre mot de passe',
  'msg_enter_old_password': 'Saisissez votre ancien mot de passe',
  'msg_enter_new_password': 'Saisissez votre nouveau mot de passe',
  'msg_enter_confirm_password': 'Saisissez le mot de passe de confirmation',
  'msg_password_limit': 'Le mot de passe doit contenir 8 caractères minimum',
  'msg_password_max_limit':
      'Le mot de passe doit contenir 15 caractères maximum',
  'msg_new_password_limit':
      'Le nouveau mot de passe doit contenir 8 caractères minimum',
  'msg_confirm_password_limit':
      'Le mot de passe de confirmation doit contenir 8 caractères minimum',
  'msg_password_not_match':
      'Le mot de passe et le mot de passe de confirmation doivent être identiques',
  'msg_new_password_not_match':
      'Le nouveau mot de passe et le mot de passe de confirmation doivent être identiques',
  'msg_country_select': 'Sélectionnez un pays',
  'msg_select_profile_photo': 'Sélectionnez une photo de profil',
  'msg_enter_traveling_from': 'Saisissez un point de départ',
  'msg_enter_traveling_to': 'Saisissez une destination',
  'msg_same_country':
      'Voyager depuis et voyager vers des pays ne peuvent pas être les mêmes',
  'msg_no_data_found': 'Aucune donnée trouvée',
  'msg_accept_terms_condition': 'Veuillez accepter les termes et conditions',
  'msg_select_dob': 'Sélectionnez la date de naissance',
  'msg_select_country': 'Choisissez le pays',
  'lbl_alert': 'ALERTE',
  'lbl_more_information': 'Ce pays a plus d\'informations sur les voyages',
  'lbl_click_here': 'CLIQUEZ ICI',
  'lbl_none': 'Aucun',
  'lbl_not_required': 'Non requis',
  'lbl_home_content':
      'Entièrement vacciné signifie que vous avez reçu la dose complète d\'un vaccin approuvé.'
          '\n\nPar exemple Pfizer BioNTech = 2 doses, Moderna = 2 doses, Janssen = 1 dose.'
          '\nVous êtes considéré comme totalement vacciné 2 semaines après votre dernière dose. Si vous avez été partiellement vacciné ou si vous voyagez dans les 2 semaines suivant votre dernière dose, on considère que vous n\'êtes pas vacciné.',
  'lbl_share_app': 'Partager Berbé',
  'lbl_share': 'Partager',
  'lbl_share_content':
      'Consultez les dernières règles de voyage en vigueur d\'un pays à l\'autre avec Berbe. C\'est rapide, simple, précis et totalement gratuit. Rendez-vous sur https://berbe.net Berbe, le voyage en toute sérénité !',
  'lbl_accept': 'Accept ',
  'lbl_terms_condition': 'Terms & Conditions',
  'msg_verify_email':
      'We have sent an activation link to your email. Please activate your account to Sign in. If you do not receive a confirmation email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
  'msg_reset_password':
      'We have sent an reset password link to your email. If you do not receive an email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
};
