const Map<String, String> stGreek = {
  'hint_enter_email': 'Email',
  'hint_password': 'Κωδικός πρόσβασης',
  'hint_old_password': 'Παλιός Κωδικός Πρόσβασης',
  'hint_new_password': 'Νέος Κωδικός Πρόσβασης',
  'hint_confirm_password': 'Επιβεβαίωση Κωδικού Πρόσβασης',
  'hint_full_name': 'Ονοματεπώνυμο*',
  'hint_dob': 'Ημερομηνία Γέννησης*',
  'hint_phone_number': 'Αριθμός τηλεφώνου*',
  'hint_country_selection': 'Επιλογή Χώρας*',
  'hint_traveling_from': 'Χώρα αναχώρησης;',
  'hint_traveling_to': 'Χώρα προορισμού;',
  'lbl_forgot_password': 'Ξεχάσατε τον κωδικό?',
  'lbl_forgot_password_title': 'Ξεχάσατε τον κωδικό',
  'lbl_change_password': 'Αλλαγή κωδικού πρόσβασης',
  'lbl_delete_account': 'Διαγραφή λογαριασμού',
  'lbl_dont_have_account': 'Δεν έχετε λογαριασμό; ',
  'lbl_already_have_account': 'Έχετε ήδη λογαριασμό; ',
  'lbl_accept_term': 'Αποδοχή Όρων & Προϋποθέσεων',
  'lbl_sign_up': 'Εγγραφή',
  'lbl_sign_in': 'Σύνδεση',
  'lbl_login': 'Σύνδεση',
  'lbl_logout': 'Αποσύνδεση',
  'lbl_ok': 'OK',
  'lbl_submit': 'Υποβολή',
  'lbl_save': 'Αποθήκευση',
  'lbl_verify_email': 'Επιβεβαίωση Email',
  'lbl_reset_password': 'Επαναφέρετε τον κωδικό πρόσβασης',
  'lbl_home': 'Αρχική',
  'lbl_my_profile': 'Το Προφίλ Μου',
  'lbl_language_selection': 'Επιλογή Γλώσσας',
  'lbl_notification': 'Ειδοποίηση',
  'lbl_are_you_vaccinated': 'Έχετε Εμβολιαστεί;',
  'lbl_search_details': 'Αναζήτηση Λεπτομερειών',
  'lbl_travel_rules_from': 'Κανόνες Ταξιδιού Από',
  'lbl_to': 'προς',
  'lbl_required_test': 'Απαιτούμενο Τεστ',
  'lbl_test_time': 'Χρόνος Τεστ',
  'lbl_age_reqiured_test': 'Ελάχιστη Απαιτούμενη Ηλικία Για Τεστ',
  'lbl_quarantine_required': 'Απαιτείται Καραντίνα',
  'lbl_additional_doc_required': 'Απαιτούνται πρόσθετα έγγραφα',
  'lbl_link_submit_doc': 'Σύνδεσμος για υποβολή εγγράφου',
  'lbl_more_info_about_result':
      'Περισσότερες λεπτομέρειες για τις προϋποθέσεις εισόδου',
  'lbl_test_required_for_country': 'Απαιτείται Τεστ Για',
  'lbl_session_expired': 'Η Συνεδρία Έληξε',
  'lbl_logout_msg': 'Θέλετε σίγουρα να αποσυνδεθείτε;',
  'lbl_cancel': 'Ακύρωση',
  'lbl_yes': 'Ναι',
  'lbl_no': 'Όχι',
  'lbl_days': 'Ημέρες',
  'lbl_day': 'Ημέρα',
  'lbl_year': 'Έτος',
  'lbl_years': 'Έτη',
  'lbl_session_expired_msg':
      'Η συνεδρία έληξε επειδή έχετε συνδεθεί σε άλλη συσκευή.',
  'lbl_within_last': 'Εντός των τελευταίων',
  'lbl_hours_of_departure': 'Ώρες αναχώρησης',
  'lbl_pfl_required': 'Τα στοιχεία του επιβάτη απαιτούνται εκ των προτέρων',
  'lbl_pfl_not_required':
      'Τα στοιχεία του επιβάτη δεν απαιτούνται εκ των προτέρων',
  'lbl_before_arrival_in': 'Πριν από την άφιξη σε',
  'lbl_on_arrival_in': 'Κατά την άφιξη σε',
  'lbl_select_image': 'Επιλέξτε Εικόνα',
  'lbl_camera': 'ΦΩΤΟΓΡΑΦΙΚΗ ΜΗΧΑΝΗ',
  'lbl_gallery': 'Εκθεσιακός χώρος',
  'lbl_update_app': 'Ενημέρωση εφαρμογής',
  'lbl_not_now': 'Οχι τώρα',
  'msg_something_went_wrong': 'Κάτι πήγε στραβά.',
  'msg_new_update': 'Η νέα ενημέρωση είναι διαθέσιμη τώρα.',
  'msg_force_update': 'Πρέπει να ενημερώσετε την εφαρμογή χειροκίνητα',
  'msg_check_connection': 'Ελέγξτε τη σύνδεση σας στο διαδίκτυο.',
  'msg_enter_full_name': 'Παρακαλώ εισάγετε το ονοματεπώνυμο',
  'msg_name_length':
      'Το όνομα δεν πρέπει να αποτελείται από περισσότερους από 70 χαρακτήρες',
  'msg_enter_email': 'Παρακαλώ εισάγετε το email',
  'msg_enter_valid_email': 'Παρακαλώ εισάγετε ένα έγκυρο email',
  'msg_enter_phone_number': 'Παρακαλώ εισάγετε έναν αριθμό τηλεφώνου',
  'msg_enter_valid_phone_number':
      'Παρακαλώ εισάγετε έναν έγκυρο αριθμό τηλεφώνου',
  'msg_phone_number_limit': 'Απαιτούνται τουλάχιστον 8 ψηφία',
  'msg_phone_number_max_limit': 'Απαιτούνται το πολύ 15 ψηφία',
  'msg_enter_password': 'Παρακαλώ εισάγετε τον κωδικό πρόσβασης',
  'msg_enter_old_password': 'Παρακαλώ εισάγετε τον παλιό κωδικό πρόσβασης',
  'msg_enter_new_password': 'Παρακαλώ εισάγετε τον νέο κωδικό πρόσβασης',
  'msg_enter_confirm_password':
      'Παρακαλώ εισάγετε την επιβεβαίωση κωδικού πρόσβασης',
  'msg_password_limit':
      'Ο κωδικός πρόσβασης πρέπει να αποτελείται από τουλάχιστον 8 χαρακτήρες',
  'msg_password_max_limit':
      'Ο κωδικός πρόσβασης πρέπει να αποτελείται το πολύ από 15 χαρακτήρες',
  'msg_new_password_limit':
      'Ο νέος κωδικός πρόσβασης πρέπει να αποτελείται από τουλάχιστον 8 χαρακτήρες',
  'msg_confirm_password_limit':
      'Η επιβεβαίωση κωδικού πρόσβασης πρέπει να αποτελείται από τουλάχιστον 8 χαρακτήρες',
  'msg_password_not_match':
      'Ο κωδικός πρόσβασης και ο κωδικός επιβεβαίωσης πρέπει να είναι ίδιοι',
  'msg_new_password_not_match':
      'Ο νέος κωδικός πρόσβασης και η επιβεβαίωση κωδικού πρόσβασης πρέπει να είναι ίδιοι',
  'msg_country_select': 'Παρακαλώ επιλέξτε χώρα',
  'msg_select_profile_photo': 'Παρακαλώ επιλέξτε εικόνα προφίλ',
  'msg_enter_traveling_from': 'Παρακαλώ εισάγετε το σημείο αναχώρησης',
  'msg_enter_traveling_to': 'Παρακαλώ εισάγετε το σημείο άφιξης',
  'msg_same_country':
      'Το ταξίδι από και το ταξίδι σε χώρες δεν μπορεί να είναι το ίδιο',
  'msg_no_data_found': 'Δεν Βρέθηκαν ΔεδομέναL',
  'msg_accept_terms_condition':
      'Παρακαλούμε αποδεχτείτε τους όρους και τις προϋποθέσεις',
  'msg_select_dob': 'Επιλέξτε ημερομηνία γέννησης',
  'msg_select_country': 'Επιλέξτε χώρα',
  'lbl_alert': 'ΣΥΝΑΓΕΡΜΟΣ',
  'lbl_more_information':
      'Αυτή η χώρα έχει περισσότερες ταξιδιωτικές πληροφορίες',
  'lbl_click_here': 'ΚΑΝΤΕ ΚΛΙΚ ΕΔΩ',
  'lbl_none': 'Κανένας',
  'lbl_not_required': 'Δεν απαιτείται',
  'lbl_home_content':
      'Πλήρως εμβολιασμένος σημαίνει ότι έχετε λάβει την πλήρη δόση ενός εγκεκριμένου εμβολίου.'
          '\nΓια παράδειγμα: Pfizer BioNTech = 2 δόσεις, Moderna = 2 δόσεις, Janssen = 1 δόση.'
          '\nΘεωρείστε Πλήρως Εμβολιασμένος 2 εβδομάδες μετά την τελική σας δόση. Εάν έχετε εμβολιαστεί μερικώς ή ταξιδεύετε εντός 2 εβδομάδων από την τελική δόση σας, θεωρείστε Ανεμβολίαστος.',
  'lbl_share_app': 'Μοιραστείτε το Berbe',
  'lbl_share': 'Μερίδιο',
  'lbl_share_content':
      'Δείτε τους πιο πρόσφατους ταξιδιωτικούς κανόνες από χώρα σε χώρα με το Berbe. Είναι γρήγορο, απλό, ακριβές και εντελώς δωρεάν. Αποκτήστε το στο https://berbe.net Το Berbe, κάνει το ταξίδι απλό!',
  'lbl_accept': 'Accept ',
  'lbl_terms_condition': 'Terms & Conditions',
  'msg_verify_email':
      'We have sent an activation link to your email. Please activate your account to Sign in. If you do not receive a confirmation email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
  'msg_reset_password':
      'We have sent an reset password link to your email. If you do not receive an email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
};
