const Map<String, String> stGerman = {
  'hint_enter_email': 'E-Mail-Adresse',
  'hint_password': 'Passwort',
  'hint_old_password': 'Altes Passwort',
  'hint_new_password': 'Neues Passwort',
  'hint_confirm_password': 'Passwort bestätigen',
  'hint_full_name': 'Vollständiger Name*',
  'hint_dob': 'Geburtsdatum*',
  'hint_phone_number': 'Telefonnummer*',
  'hint_country_selection': 'Länderauswahl',
  'hint_traveling_from': 'Von wo reisen Sie an?',
  'hint_traveling_to': 'In welches Land reisen Sie?',
  'lbl_forgot_password': 'Passwort vergessen?',
  'lbl_forgot_password_title': 'Passwort vergessen',
  'lbl_change_password': 'Passwort ändern',
  'lbl_delete_account': 'Konto löschen',
  'lbl_dont_have_account': 'Noch kein Konto? ',
  'lbl_already_have_account': 'Sie haben bereits ein Konto? ',
  'lbl_accept_term': 'AGB´s bestätigen',
  'lbl_sign_up': 'Registrieren',
  'lbl_sign_in': 'Anmelden',
  'lbl_login': 'Einloggen',
  'lbl_logout': 'Logout',
  'lbl_ok': 'Ok',
  'lbl_submit': 'Absenden',
  'lbl_save': 'Speichern',
  'lbl_verify_email': 'E-Mail-Adresse bestätigen',
  'lbl_reset_password': 'Passwort zurücksetzen',
  'lbl_home': 'Home',
  'lbl_my_profile': 'Mein Profil',
  'lbl_language_selection': 'Sprachauswahl',
  'lbl_notification': 'Benachrichtigungen',
  'lbl_are_you_vaccinated': 'Sind Sie geimpft?',
  'lbl_search_details': 'Suchdetails',
  'lbl_travel_rules_from': 'Reisebestimmungen von',
  'lbl_to': 'Nach',
  'lbl_required_test': 'Erforderlicher Test',
  'lbl_test_time': 'Gültigkeitsdauer Corona-Test',
  'lbl_age_reqiured_test': 'Corona-Test erforderlich für Personen ab',
  'lbl_quarantine_required': 'Quarantäne erforderlich',
  'lbl_additional_doc_required': 'Zusätzliche(s) Dokument(e) erforderlich',
  'lbl_link_submit_doc': 'Link zur Einreichung der Dokumente',
  'lbl_more_info_about_result':
      'Mehr Informationen zu den Einreisebestimmungen',
  'lbl_test_required_for_country': 'Test erforderlich für',
  'lbl_session_expired': 'Sitzung ist abgelaufen',
  'lbl_logout_msg': 'Aus diesem Konto ausloggen?',
  'lbl_cancel': 'Abbrechen',
  'lbl_yes': 'Ja',
  'lbl_no': 'Nein',
  'lbl_days': 'Tage',
  'lbl_day': 'Tag',
  'lbl_year': 'Jahr',
  'lbl_years': 'Jahre',
  'lbl_session_expired_msg':
      'Sitzung wurde aufgrund weiterer Anmeldung auf einem anderen Gerät beendet.',
  'lbl_within_last': 'Innerhalb der letzten',
  'lbl_hours_of_departure': 'Stunden vor Abreise',
  'lbl_pfl_required': 'Vorabinformationen zum Reisenden erforderlich',
  'lbl_pfl_not_required': 'Vorabinformationen zum Reisenden nicht erforderlich',
  'lbl_before_arrival_in': 'Vor Ankunft in',
  'lbl_on_arrival_in': 'Bei Ankunft in',
  'lbl_select_image': 'Bild auswählen',
  'lbl_camera': 'Kamera',
  'lbl_gallery': 'Galerie',
  'lbl_update_app': 'App aktualisieren',
  'lbl_not_now': 'Nicht jetzt',
  'msg_something_went_wrong': 'Etwas ist schiefgelaufen.',
  'msg_new_update': 'Neues Update ist jetzt verfügbar.',
  'msg_force_update': 'Update erzwingen',
  'msg_check_connection': 'Bitte überprüfen Sie Ihre Internetverbindung.',
  'msg_enter_full_name': 'Bitte tragen Sie Ihren vollständigen Namen ein',
  'msg_name_length': 'Name sollte nicht länger als 70 Zeichen sein',
  'msg_enter_email': 'Bitte E-Mail-Adresse eingeben',
  'msg_enter_valid_email': 'Bitte gültige E-Mail-Adresse eingeben',
  'msg_enter_phone_number': 'Bitte Telefonnummer eingeben',
  'msg_enter_valid_phone_number': 'Bitte gültige Telefonnummer eingeben',
  'msg_phone_number_limit': 'Muss mindestens 8 Zeichen lang sein',
  'msg_phone_number_max_limit': 'Darf höchstens 15 Zeichen lang sein',
  'msg_enter_password': 'Bitte Passwort eingeben',
  'msg_enter_old_password': 'Bitte altes Passwort eingeben',
  'msg_enter_new_password': 'Bitte neues Passwort eingeben',
  'msg_enter_confirm_password': 'Bitte Passwort bestätigen',
  'msg_password_limit': 'Passwort muss mindestens 8 Zeichen lang sein',
  'msg_password_max_limit': 'Passwort sollte nicht länger als 15 Zeichen sein',
  'msg_new_password_limit':
      'Neues Passwort muss mindestens 8 Zeichen lang sein',
  'msg_confirm_password_limit':
      'Bestätigungspasswort muss mindestens 8 Zeichen lang sein',
  'msg_password_not_match':
      'Passwort und Bestätigungspasswort müssen identisch sein',
  'msg_new_password_not_match':
      'Neues Passwort und Bestätigungspasswort müssen übereinstimmen',
  'msg_country_select': 'Bitte Land wählen',
  'msg_select_profile_photo': 'Bitte Profilbild wählen',
  'msg_enter_traveling_from': 'Bitte Abreiseort eingeben',
  'msg_enter_traveling_to': 'Bitte Reiseziel eingeben',
  'msg_same_country': 'Reisen aus und Reisen in Länder können nicht gleich sein',
  'msg_no_data_found': 'Daten wurden nicht gefunden',
  'msg_accept_terms_condition':
      'Bitte akzeptieren Sie die Allgemeinen Geschäftsbedingungen',
  'msg_select_dob': 'Geburtsdatum auswählen',
  'msg_select_country': 'Land auswählen',
  'lbl_alert': 'ALARM',
  'lbl_more_information': 'Dieses Land hat mehr Reiseinformationen',
  'lbl_click_here': 'KLICK HIER',
  'lbl_none': 'Keiner',
  'lbl_not_required': 'Nicht benötigt',
  'lbl_home_content':
      'Vollständige Impfung steht dafür, dass Sie die volle Dosis eines anerkannten und zugelassenen Impfstoffs verabreicht bekommen haben.'
          '\n\nBeispielsweise Pfizer BioNTech = 2 Impfdosen, Moderna = 2 Impfdosen, Janssen = 1 Impfdosis.'
          '\nAls vollständig geimpft gelten Sie bereits 2 Wochen nach Ihrer letzten Dosis. Falls Sie nur Teilimpfungen erhalten haben oder binnen 2 Wochen nach Ihrer letzten Dosis verreisen, gelten Sie als nicht geimpft.',
  'lbl_share_app': 'Berbe teilen',
  'lbl_share': 'Teilen',
  'lbl_share_content': 'Finden Sie mit Berbe die jüngsten Reisebestimmungen für jedes Land. Schnell, einfach, genau und völlig kostenlos. Besuchen Sie https://berbe.net Berbe macht das Reisen einfach!',
  'lbl_accept': 'Accept ',
  'lbl_terms_condition': 'Terms & Conditions',
  'msg_verify_email':
  'We have sent an activation link to your email. Please activate your account to Sign in. If you do not receive a confirmation email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
  'msg_reset_password':
  'We have sent an reset password link to your email. If you do not receive an email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
};
