const Map<String, String> stHindi = {
  'hint_enter_email': 'ईमेल आईडी',
  'hint_password': 'पासवर्ड',
  'hint_old_password': 'पुराना पासवर्ड',
  'hint_new_password': 'नया पासवर्ड',
  'hint_confirm_password': 'पासवर्ड कन्फर्म  करें',
  'hint_full_name': 'पूरा नाम*',
  'hint_dob': 'जन्म तिथि*',
  'hint_phone_number': 'फोन नंबर*',
  'hint_country_selection': 'देश चुनें*',
  'hint_traveling_from': 'किस देश से यात्रा कर रहे हैं?',
  'hint_traveling_to': 'किस देश तक यात्रा कर रहे हैं?',
  'lbl_forgot_password': 'पासवर्ड भूल गए?',
  'lbl_forgot_password_title': 'पासवर्ड भूल गए',
  'lbl_change_password': 'पासवर्ड बदलें',
  'lbl_delete_account': 'खाता हटा दो',
  'lbl_dont_have_account': 'कोई अकाउंट नहीं है? ',
  'lbl_already_have_account': 'पहले से ही अकाउंट मौजूद है? ',
  'lbl_accept_term': 'नियम व शर्तों को स्वीकृत करें',
  'lbl_sign_up': 'साइन अप करें',
  'lbl_sign_in': 'साइन इन करें',
  'lbl_login': 'लॉगिन करें',
  'lbl_logout': 'लॉग आउट करें',
  'lbl_ok': 'ठीक है',
  'lbl_submit': 'जमा करें',
  'lbl_save': 'सहेजें',
  'lbl_verify_email': 'ईमेल वेरीफाई करें',
  'lbl_reset_password': 'पासवर्ड रीसेट',
  'lbl_home': 'होम',
  'lbl_my_profile': 'मेरी प्रोफाइल',
  'lbl_language_selection': 'भाषा चुनें',
  'lbl_notification': 'नोटिफिकेशन',
  'lbl_are_you_vaccinated': 'क्या आप वैक्सीनेटड हैं?',
  'lbl_search_details': 'डिटेल ढूंढें',
  'lbl_travel_rules_from': 'के यात्रा नियम',
  'lbl_to': 'तक',
  'lbl_required_test': 'जरुरी टेस्ट',
  'lbl_test_time': 'टेस्ट समय',
  'lbl_age_reqiured_test': 'टेस्ट के लिए जरुरी न्यूनतम आयु',
  'lbl_quarantine_required': 'जरुरी क्वारंटाइन',
  'lbl_additional_doc_required': 'जरुरी अतिरिक्त डॉक्यूमेंट(टों)',
  'lbl_link_submit_doc': 'डॉक्यूमेंट जमा करने की लिंक',
  'lbl_more_info_about_result': 'प्रवेश जरूरतों के बारे में अधिक जानकारी',
  'lbl_test_required_for_country': 'के लिए टेस्ट जरुरी',
  'lbl_session_expired': 'सेशन समाप्त',
  'lbl_logout_msg': 'क्या आप सही में लॉग आउट करना चाहते हैं?',
  'lbl_cancel': 'रद्द करें',
  'lbl_yes': 'हां',
  'lbl_no': 'नहीं',
  'lbl_days': 'दिनों',
  'lbl_day': 'दिन',
  'lbl_year': 'वर्ष',
  'lbl_years': 'वर्षों',
  'lbl_session_expired_msg':
      'दूसरी डिवाइस में लॉग इन करने से सेशन समाप्त हो गया था',
  'lbl_within_last': 'के अंदर',
  'lbl_hours_of_departure': 'डिपार्चर के घंटे',
  'lbl_pfl_required': 'यात्री की अग्रिम जानकारी की जरुरत है',
  'lbl_pfl_not_required': 'यात्री की अग्रिम जानकारी की जरुरत नहीं है',
  'lbl_before_arrival_in': 'में आगमन से पहले',
  'lbl_on_arrival_in': 'आगमन पर',
  'lbl_select_image': 'छवि चुने',
  'lbl_camera': 'कैमरा',
  'lbl_gallery': 'गेलरी',
  'lbl_update_app': 'अपडेट ऐप',
  'lbl_not_now': 'अभी नहीं',
  'msg_something_went_wrong': 'कोई गलती हुई है।',
  'msg_new_update': 'नया अपडेट अब उपलब्ध है।',
  'msg_force_update': 'ऐप को जबरदस्ती अपडेट करने की जरुरत है',
  'msg_check_connection': 'अपना इंटरनेट कनेक्शन चेक करें।',
  'msg_enter_full_name': 'कृपया पूरा नाम भरें',
  'msg_name_length': 'नाम में 70 से अधिक अक्षर नहीं होने चाहिए',
  'msg_enter_email': 'कृपया ईमेल भरें',
  'msg_enter_valid_email': 'कृपया एक वैध ईमेल भरें',
  'msg_enter_phone_number': 'कृपया फोन नंबर भरें',
  'msg_enter_valid_phone_number': 'कृपया एक वैध फोन नंबर भरें',
  'msg_phone_number_limit': 'न्यूनतम 8 अंक जरुरी हैं',
  'msg_phone_number_max_limit': 'अधिकतम 15 अंक जरुरी हैं',
  'msg_enter_password': 'कृपया पासवर्ड भरें',
  'msg_enter_old_password': 'कृपया पुराना पासवर्ड भरें',
  'msg_enter_new_password': 'कृपया नया पासवर्ड भरें',
  'msg_enter_confirm_password': 'कृपया कन्फर्म पासवर्ड भरें',
  'msg_password_limit': 'पासवर्ड ने कम से कम 8 अक्षर होने चाहिए',
  'msg_password_max_limit': 'पासवर्ड अधिकतम 15 अक्षर का होना चाहिए',
  'msg_new_password_limit': 'नए पासवर्ड में कम से कम 8 अक्षर होने चाहिए',
  'msg_confirm_password_limit':
      'कन्फर्म पासवर्ड में कम से कम 8 अक्षर होने चाहिए',
  'msg_password_not_match': 'पासवर्ड और कन्फर्म पासवर्ड एक ही होना चाहिए',
  'msg_new_password_not_match':
      'नया पासवर्ड और कन्फर्म पासवर्ड एक समान होना चाहिए',
  'msg_country_select': 'कृपया देश चुनें',
  'msg_select_profile_photo': 'कृपया प्रोफाइल फोटो चुनें',
  'msg_enter_traveling_from': 'कृपया भरें, से यात्रा कर रहे हैं',
  'msg_enter_traveling_to': 'कृपया भरें, की यात्रा पर जा रहे हैं',
  'msg_same_country': 'देशों से यात्रा करना और यात्रा करना समान नहीं हो सकता',
  'msg_no_data_found': 'कोई डाटा नहीं मिला',
  'msg_accept_terms_condition': 'कृपया नियम और शर्तें स्वीकार करें',
  'msg_select_dob': 'जन्म तिथि चुनें',
  'msg_select_country': 'देश चुनें',
  'lbl_alert': 'चेतावनी',
  'lbl_more_information': 'इस देश में यात्रा की अधिक जानकारी है',
  'lbl_click_here': 'यहाँ क्लिक करें',
  'lbl_none': 'कोई नहीं',
  'lbl_not_required': 'आवश्यक नहीं',
  'lbl_home_content':
      'पूरी तरह से टीकाकृत का मतलब है कि आपने एक स्वीकृत टीके की पूरी खुराक ले ली है।'
          '\n\nउदाहरण के लिए फाइजर बायोएनटेक = 2 ​​खुराक, मॉडर्ना = 2 खुराक, जानसेन = 1 खुराक।'
          '\nआपकी अंतिम खुराक के 2 सप्ताह बाद आपको पूरी तरह से टीकाकृत माना जाता है। यदि आपको आंशिक रूप से टीका लगाया गया है या आप अपनी अंतिम खुराक के 2 सप्ताह के भीतर यात्रा कर रहे हैं, तो आपको टीकाकृत नहीं माना जाएगा।',
  'lbl_share_app': 'Berbe साझा करें',
  'lbl_share': 'साझा करना',
  'lbl_share_content': 'Berbe के जरिए एक देश से दूसरे देश में यात्रा के लिए  नवीनतम नियमों की जाँच करें। यह तेज़, सरल, सटीक और पूरी तरह से मुफ़्त है। इसे https://berbe.net पर प्राप्त करें। Berbe, यात्रा को आसान बनाता है!',
  'lbl_accept': 'Accept ',
  'lbl_terms_condition': 'Terms & Conditions',
  'msg_verify_email':
  'We have sent an activation link to your email. Please activate your account to Sign in. If you do not receive a confirmation email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
  'msg_reset_password':
  'We have sent an reset password link to your email. If you do not receive an email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
};
