const Map<String, String> stItalian = {
  'hint_enter_email': 'Nome Utente',
  'hint_password': 'Password',
  'hint_old_password': 'Vecchia Password',
  'hint_new_password': 'Nuova Password',
  'hint_confirm_password': 'Conferma Password',
  'hint_full_name': 'Nome e Cognome*',
  'hint_dob': 'Data di Nascita*',
  'hint_phone_number': 'Numero telefonico*',
  'hint_country_selection': 'Selezione Paese*',
  'hint_traveling_from': 'Paese di provenienza?',
  'hint_traveling_to': 'Paese di destinazione?',
  'lbl_forgot_password': 'Password dimenticata?',
  'lbl_forgot_password_title': 'Password dimenticata',
  'lbl_change_password': 'Cambia password',
  'lbl_delete_account': 'Eliminare l account',
  'lbl_dont_have_account': 'Non hai un account? ',
  'lbl_already_have_account': 'Hai già un account? ',
  'lbl_accept_term': 'Accetta Termini e Condizioni',
  'lbl_sign_up': 'Iscriviti',
  'lbl_sign_in': 'Accedi',
  'lbl_login': 'Entra',
  'lbl_logout': 'Esci',
  'lbl_ok': 'Ok',
  'lbl_submit': 'Invia',
  'lbl_save': 'Salva',
  'lbl_verify_email': 'Verifica Email',
  'lbl_reset_password': 'Resetta la password',
  'lbl_home': 'Pagina Iniziale',
  'lbl_my_profile': 'Il mio Profilo',
  'lbl_language_selection': 'Selezione Lingua',
  'lbl_notification': 'Notifiche',
  'lbl_are_you_vaccinated': 'Sei Vaccinato?',
  'lbl_search_details': 'Dettagli di Ricerca',
  'lbl_travel_rules_from': 'Regole di Viaggio da',
  'lbl_to': 'a',
  'lbl_required_test': 'Test Richiesto',
  'lbl_test_time': 'Tempo di Prova',
  'lbl_age_reqiured_test': 'Età minima richiesta per il Test',
  'lbl_quarantine_required': 'Quarantena Richiesta',
  'lbl_additional_doc_required': 'Documento(i)  ulteriore richiesto',
  'lbl_link_submit_doc': 'Link per inviare documento',
  'lbl_more_info_about_result':
      'Ulteriori informazioni circa le regole di ingresso',
  'lbl_test_required_for_country': 'Test Richiesto per',
  'lbl_session_expired': 'Sessione Scaduta',
  'lbl_logout_msg': 'Sei sicuro di voler uscire?',
  'lbl_cancel': 'Esci',
  'lbl_yes': 'Sì',
  'lbl_no': 'No',
  'lbl_days': 'Giorni',
  'lbl_day': 'Giorno',
  'lbl_year': 'Anno',
  'lbl_years': 'Anni',
  'lbl_session_expired_msg':
      'La sessione è scaduta perché sei connesso a un altro dispositivo.',
  'lbl_within_last': 'Entro ultimo',
  'lbl_hours_of_departure': 'Orari di partenza',
  'lbl_pfl_required': 'Sono richieste informazioni anticipate sul passeggero',
  'lbl_pfl_not_required':
      'Non sono richieste informazioni anticipate sul passeggero',
  'lbl_before_arrival_in': 'Prima dell\'arrivo a',
  'lbl_on_arrival_in': 'In arrivo a',
  'lbl_select_image': 'Seleziona Immagine',
  'lbl_camera': 'Telecamera',
  'lbl_gallery': 'Galleria',
  'lbl_update_app': 'Aggiorna app',
  'lbl_not_now': 'Non adesso',
  'msg_something_went_wrong': 'Qualcosa è andato storto',
  'msg_new_update': 'Nuovo aggiornamento disponibile ora',
  'msg_force_update': 'Necessario aggiornamento forzato della app',
  'msg_check_connection': 'Controlla la tua connessione internet',
  'msg_enter_full_name': 'Prego inserisci nome e cognome',
  'msg_name_length': 'Il nome non dovrebbe essere superiore a 70 caratteri',
  'msg_enter_email': 'Prego inserisci email',
  'msg_enter_valid_email': 'Prego inserisci una email valida',
  'msg_enter_phone_number': 'Prego inserisci numero telefonico',
  'msg_enter_valid_phone_number': 'Prego inserisci un numero telefonico valido',
  'msg_phone_number_limit': 'Sono richieste almeno 8 cifre',
  'msg_phone_number_max_limit': 'È richiesto un numero massimo di 15 cifre',
  'msg_enter_password': 'Prego inserisci password',
  'msg_enter_old_password': 'Prego inserisci vecchia password',
  'msg_enter_new_password': 'Prego inserisci nuova password',
  'msg_enter_confirm_password': 'Prego conferma password',
  'msg_password_limit': 'La password deve avere almeno 8 caratteri',
  'msg_password_max_limit':
      'La password dovrebbe avere 15 caratteri al massimo',
  'msg_new_password_limit': 'La nuova password deve avere almeno 8 caratteri',
  'msg_confirm_password_limit':
      'Conferma password deve avere almeno 8 caratteri',
  'msg_password_not_match':
      'La password e la password di conferma devono essere uguali',
  'msg_new_password_not_match':
      'Nuova password e conferma password devono essere uguali',
  'msg_country_select': 'Prego seleziona paese',
  'msg_select_profile_photo': 'Prego seleziona foto del profilo',
  'msg_enter_traveling_from': 'Prego inserisci provenienza',
  'msg_enter_traveling_to': 'Prego inserisi destinazione',
  'msg_same_country': 'Viaggiare da e viaggiare verso paesi non può essere lo stesso',
  'msg_no_data_found': 'Nessun Dato Trovato',
  'msg_accept_terms_condition': 'Si prega di accettare termini e condizioni',
  'msg_select_dob': 'Seleziona la data di nascita',
  'msg_select_country': 'Seleziona il paese',
  'lbl_alert': 'METTERE IN GUARDIA',
  'lbl_more_information': 'Questo paese ha più informazioni di viaggio',
  'lbl_click_here': 'CLICCA QUI',
  'lbl_none': 'Nessuno',
  'lbl_not_required': 'Non richiesto',
  'lbl_home_content':
      'Vaccinazione completa significa aver ricevuto la dose completa di un vaccino approvato.'
          '\n\nPer esempio Pfizer BioNtech = 3 dosi, Moderna = 3 dosi, Janssen = 2 dosi.'
          '\nSi viene considerati vaccinati in modo completo 2 settimane dopo aver ricevuto l\'ultima dose. Nel caso in cui si sia vaccinati in modo parziale o nel caso in cui si stia viaggiando nelle prime 2 settimane che seguono la somministrazione dell\'ultima dose, si viene considerati \'Non vaccinati\'.',
  'lbl_share_app': 'Condividi Berbe',
  'lbl_share': 'Condividere',
  'lbl_share_content': 'Controlla con Berbe le ultime regole relative ai viaggi da un Paese all\'altro. È veloce, semplice, precisa e completamente gratuita. Scaricala su https://berbe.net Berbe rende più semplice viaggiare!',
  'lbl_accept': 'Accept ',
  'lbl_terms_condition': 'Terms & Conditions',
  'msg_verify_email':
  'We have sent an activation link to your email. Please activate your account to Sign in. If you do not receive a confirmation email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
  'msg_reset_password':
  'We have sent an reset password link to your email. If you do not receive an email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
};
