const Map<String, String> stJapanese = {
  'hint_enter_email': 'メールアドレス',
  'hint_password': 'パスワード',
  'hint_old_password': '古いパスワード',
  'hint_new_password': '新しいパスワード',
  'hint_confirm_password': 'パスワードの確認',
  'hint_full_name': '氏名',
  'hint_dob': '生年月日',
  'hint_phone_number': '電話番号※1',
  'hint_country_selection': '国名選択※1',
  'hint_traveling_from': '帰国先',
  'hint_traveling_to': '渡航先',
  'lbl_forgot_password': '検索中',
  'lbl_forgot_password_title': 'パスワードをお忘れの方',
  'lbl_change_password': 'パスワードの変更',
  'lbl_delete_account': 'アカウントを削除する',
  'lbl_dont_have_account': 'アカウントをお持ちでない方 ',
  'lbl_already_have_account': 'すでにアカウントをお持ちの方 ',
  'lbl_accept_term': '利用規約に同意する',
  'lbl_sign_up': '登録する',
  'lbl_sign_in': 'サインイン',
  'lbl_login': 'ログイン',
  'lbl_logout': 'ログアウト',
  'lbl_ok': 'OK',
  'lbl_submit': '送信',
  'lbl_save': '保存',
  'lbl_verify_email': '電子メールを確認する',
  'lbl_reset_password': 'パスワードを再設定する',
  'lbl_home': 'ホーム',
  'lbl_my_profile': 'マイプロフィール',
  'lbl_language_selection': '言語選択',
  'lbl_notification': 'お知らせ',
  'lbl_are_you_vaccinated': 'ワクチン接種はお済みですか？',
  'lbl_search_details': '詳細検索',
  'lbl_travel_rules_from': 'トラベルルール',
  'lbl_to': 'まで',
  'lbl_required_test': '必要な検査',
  'lbl_test_time': '検査時間',
  'lbl_age_reqiured_test': '検査の最低年齢',
  'lbl_quarantine_required': '検疫必須',
  'lbl_additional_doc_required': '追加で必要な書類',
  'lbl_link_submit_doc': '書類提出へのリンク',
  'lbl_more_info_about_result': '入国条件に関する詳細情報',
  'lbl_test_required_for_country': '必要なテスト',
  'lbl_session_expired': 'セッションが終了しました',
  'lbl_logout_msg': '本当にログアウトしますか？',
  'lbl_cancel': 'キャンセル',
  'lbl_yes': 'はい',
  'lbl_no': 'いいえ',
  'lbl_days': '日数',
  'lbl_day': '日',
  'lbl_year': '年',
  'lbl_years': '年',
  'lbl_session_expired_msg': '他のデバイスでログインしていたため、セッションが失効しました。',
  'lbl_within_last': '直近の',
  'lbl_hours_of_departure': '出発までの時間',
  'lbl_pfl_required': '事前旅客情報入力が必要',
  'lbl_pfl_not_required': '事前旅客情報不要',
  'lbl_before_arrival_in': '到着前',
  'lbl_on_arrival_in': '到着時',
  'lbl_select_image': '画像を選択',
  'lbl_camera': 'カメラ',
  'lbl_gallery': 'ギャラリー',
  'lbl_update_app': 'アプリを更新',
  'lbl_not_now': '今はやめろ',
  'msg_something_went_wrong': '問題が発生しました。',
  'msg_new_update': '新しいアップデートが利用可能になりました。',
  'msg_force_update': 'アプリをアップデートする必要があります',
  'msg_check_connection': 'インターネット接続を確認してください。',
  'msg_enter_full_name': 'フルネームを入力してください。',
  'msg_name_length': 'お名前は70文字以内でお願いします',
  'msg_enter_email': 'Eメールを入力してください',
  'msg_enter_valid_email': '有効なEメールを入力してください',
  'msg_enter_phone_number': '電話番号を入力してください',
  'msg_enter_valid_phone_number': '有効な電話番号を入力してください。',
  'msg_phone_number_limit': '8桁以上の数字が必要です',
  'msg_phone_number_max_limit': '最大15桁の数字が必要です',
  'msg_enter_password': 'パスワードを入力してください',
  'msg_enter_old_password': '古いパスワードを入力してください。',
  'msg_enter_new_password': '新しいパスワードを入力してください。',
  'msg_enter_confirm_password': '確認用パスワードを入力してください。',
  'msg_password_limit': 'パスワードは8文字以上です',
  'msg_password_max_limit': 'パスワードは最大15文字までです',
  'msg_new_password_limit': '新しいパスワードは8文字以上です',
  'msg_confirm_password_limit': '確認用パスワードは8文字以上です',
  'msg_password_not_match': 'パスワードと確認パスワードは同じである必要があります',
  'msg_new_password_not_match': '新しいパスワードと確認用パスワードは同じでなければなりません',
  'msg_country_select': '国を選択してください',
  'msg_select_profile_photo': 'プロフィール写真を選択してください',
  'msg_enter_traveling_from': '旅行元を入力してください',
  'msg_enter_traveling_to': '旅行先を入力してください。',
  'msg_same_country': '国からの旅行と国への旅行は同じにすることはできません',
  'msg_no_data_found': 'データがありません',
  'msg_accept_terms_condition': '利用規約に同意してください',
  'msg_select_dob': '生年月日を選択',
  'msg_select_country': '国を選択',
  'lbl_alert': 'アラート',
  'lbl_more_information': 'この国はより多くの旅行情報を持っています',
  'lbl_click_here': 'ここをクリック',
  'lbl_none': 'なし',
  'lbl_not_required': '不要',
  'lbl_home_content': '接種完了とは、承認されたワクチンを全て接種したことを意味します。'
      '\n\n例：ファイザー・バイオンテック＝2回分、モデルナ＝2回分、ヤンセン＝1回分。'
      '\n最終投与から2週間後に接種完了とみなされます。部分接種の場合、または最終接種から2週間以内に渡航する場合は、未接種とみなされます。',
  'lbl_share_app': 'Berbeを共有する',
  'lbl_share': '共有',
  'lbl_share_content': 'Berbeで国ごとの最新の渡航に関する規定をチェックしましょう。迅速、簡単、正確、そして完全に無料です。https://berbe.net で入手できます。「Berbeは、旅をシンプルにする」',
  'lbl_accept': 'Accept ',
  'lbl_terms_condition': 'Terms & Conditions',
  'msg_verify_email':
  'We have sent an activation link to your email. Please activate your account to Sign in. If you do not receive a confirmation email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
  'msg_reset_password':
  'We have sent an reset password link to your email. If you do not receive an email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
};
