const Map<String, String> stPortuguese = {
  'hint_enter_email': 'ID de e-mail',
  'hint_password': 'Palavra-passe',
  'hint_old_password': 'Palavra-passe antiga',
  'hint_new_password': 'Nova palavra-passe',
  'hint_confirm_password': 'Confirmar palavra-passe',
  'hint_full_name': 'Nome completo*',
  'hint_dob': 'Data de nascimento*',
  'hint_phone_number': 'Número de telefone*',
  'hint_country_selection': 'Seleção de país*',
  'hint_traveling_from': 'País de Origem',
  'hint_traveling_to': 'País de Destino',
  'lbl_forgot_password': 'Esqueceu-se da sua palavra-passe?',
  'lbl_forgot_password_title': 'Esqueceu-se da sua palavra-passe',
  'lbl_change_password': 'Alterar palavra-passe',
  'lbl_delete_account': 'Deletar conta',
  'lbl_dont_have_account': 'Não tem uma conta? ',
  'lbl_already_have_account': 'Já tem uma conta? ',
  'lbl_accept_term': 'Aceitar termos e condições',
  'lbl_sign_up': 'Registar',
  'lbl_sign_in': 'Entrar',
  'lbl_login': 'Iniciar sessão',
  'lbl_logout': 'Terminar sessão',
  'lbl_ok': 'Ok',
  'lbl_submit': 'Enviar',
  'lbl_save': 'Guardar',
  'lbl_verify_email': 'Verificar e-mail',
  'lbl_reset_password': 'Redefinir senha',
  'lbl_home': 'Início',
  'lbl_my_profile': 'O meu perfil',
  'lbl_language_selection': 'Seleção de língua',
  'lbl_notification': 'Notificação',
  'lbl_are_you_vaccinated': 'Está vacinado/a?',
  'lbl_search_details': 'Detalhes da pesquisa',
  'lbl_travel_rules_from': 'Regras de viagem de',
  'lbl_to': 'para',
  'lbl_required_test': 'Teste exigido',
  'lbl_test_time': 'Tempo do teste',
  'lbl_age_reqiured_test': 'Idade mínima exigida para o teste',
  'lbl_quarantine_required': 'Quarentena exigida',
  'lbl_additional_doc_required': 'Documentos adicionais exigidos',
  'lbl_link_submit_doc': 'Link para enviar documentos',
  'lbl_more_info_about_result': 'Mais informações sobre o requisito de entrada',
  'lbl_test_required_for_country': 'Teste exigido para',
  'lbl_session_expired': 'Sessão expirada',
  'lbl_logout_msg': 'Tem a certeza de que quer terminar sessão?',
  'lbl_cancel': 'Cancelar',
  'lbl_yes': 'Sim',
  'lbl_no': 'Não',
  'lbl_days': 'Dias',
  'lbl_day': 'Dia',
  'lbl_year': 'Ano',
  'lbl_years': 'Anos',
  'lbl_session_expired_msg':
      'A sessão expirou porque iniciou sessão noutro dispositivo.',
  'lbl_within_last': 'Nas últimas',
  'lbl_hours_of_departure': 'Horas antes da partida',
  'lbl_pfl_required': 'São exigidas informações prévias sobre passageiros',
  'lbl_pfl_not_required':
      'Não são exigidas informações prévias sobre passageiros',
  'lbl_before_arrival_in': 'Antes da chegada a',
  'lbl_on_arrival_in': 'Na chegada a',
  'lbl_select_image': 'Selecione a imagem',
  'lbl_camera': 'Câmera',
  'lbl_gallery': 'Galeria',
  'lbl_update_app': 'Atualizar aplicativo',
  'lbl_not_now': 'Agora não',
  'msg_something_went_wrong': 'Algo correu mal.',
  'msg_new_update': 'Nova atualização disponível.',
  'msg_force_update': 'É necessário atualizar a aplicação',
  'msg_check_connection': 'Verifique a sua ligação à Internet.',
  'msg_enter_full_name': 'Por favor, insira o seu nome completo',
  'msg_name_length': 'O nome não deverá ter mais de 70 caracteres',
  'msg_enter_email': 'Por favor, insira o seu e-mail',
  'msg_enter_valid_email': 'Por favor, insira um e-mail válido',
  'msg_enter_phone_number': 'Por favor, insira o seu número de telefone',
  'msg_enter_valid_phone_number':
      'Por favor, insira um número de telefone válido',
  'msg_phone_number_limit': 'É necessário ter no mínimo 8 dígitos',
  'msg_phone_number_max_limit': 'É necessário ter no máximo 15 dígitos',
  'msg_enter_password': 'Por favor, insira a sua palavra-passe',
  'msg_enter_old_password': 'Por favor, insira a sua palavra-passe antiga',
  'msg_enter_new_password': 'Por favor, insira a sua nova palavra-passe',
  'msg_enter_confirm_password': 'Por favor, confirme a sua palavra-passe',
  'msg_password_limit': 'A palavra-passe deverá ter no mínimo 8 caracteres',
  'msg_password_max_limit':
      'A palavra-passe deverá ter no máximo 15 caracteres',
  'msg_new_password_limit':
      'A nova palavra-passe deverá ter no mínimo 8 caracteres',
  'msg_confirm_password_limit':
      'A confirmação da palavra-passe deverá ter no mínimo 8 caracteres',
  'msg_password_not_match': 'A senha e a senha de confirmação devem ser iguais',
  'msg_new_password_not_match':
      'A nova palavra-passe e a confirmação da palavra-passe devem ser iguais',
  'msg_country_select': 'Por favor, selecione o país',
  'msg_select_profile_photo': 'Por favor, selecione uma fotografia de perfil',
  'msg_enter_traveling_from': 'Por favor, insira de onde vai viajar',
  'msg_enter_traveling_to': 'Por favor, insira para onde vai viajar',
  'msg_same_country': 'Viajar de e viajar para países não pode ser o mesmo',
  'msg_no_data_found': 'Nenhuns dados encontrados',
  'msg_accept_terms_condition': 'Aceite os termos e condições',
  'msg_select_dob': 'Selecione a data de nascimento',
  'msg_select_country': 'Selecione o pais',
  'lbl_alert': 'ALERTA',
  'lbl_more_information': 'Este país tem mais informações de viagem',
  'lbl_click_here': 'CLIQUE AQUI',
  'lbl_none': 'Nenhum',
  'lbl_not_required': 'Não requerido',
  'lbl_home_content':
      'Totalmente vacinado significa que recebeu a dose completa de uma vacina aprovada.'
          '\n\nPor exemplo: Pfizer BioNTech = 2 doses, Moderna = 2 doses, Janssen = 1 dose.'
          '\nÉ considerado Totalmente Vacinado 2 semanas após a sua dose final. Se estiver parcialmente vacinado ou estiver a viajar antes de terem passado 2 semanas da sua dose final, é considerado Não Vacinado.',
  'lbl_share_app': 'Compartilhe Berbe',
  'lbl_share': 'Participação',
  'lbl_share_content': 'Verifique as mais recentes regras de viagem de país para país com a Berbe. É rápido, simples, preciso, e totalmente gratuito. Transfira a app em https://berbe.net Berbe, simplificando viagens!',
  'lbl_accept': 'Accept ',
  'lbl_terms_condition': 'Terms & Conditions',
  'msg_verify_email':
  'We have sent an activation link to your email. Please activate your account to Sign in. If you do not receive a confirmation email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
  'msg_reset_password':
  'We have sent an reset password link to your email. If you do not receive an email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
};
