const Map<String, String> stRussian = {
  'hint_enter_email': 'Идентификатор электронной почты',
  'hint_password': 'Пароль',
  'hint_old_password': 'Старый пароль',
  'hint_new_password': 'Новый пароль',
  'hint_confirm_password': 'Подтверждение пароля',
  'hint_full_name': 'ФИО*',
  'hint_dob': 'Дата рождения*',
  'hint_phone_number': 'Дата рождения*',
  'hint_country_selection': 'Выбор страны*',
  'hint_traveling_from': 'Из какой страны вы отправляетесь?',
  'hint_traveling_to': 'В какую страну вы направляетесь?',
  'lbl_forgot_password': 'Забыли пароль?',
  'lbl_forgot_password_title': 'Забыли пароль',
  'lbl_change_password': 'Изменить пароль',
  'lbl_delete_account': 'Удалить аккаунт',
  'lbl_dont_have_account': 'У вас нет аккаунта? ',
  'lbl_already_have_account': 'У вас уже есть аккаунт? ',
  'lbl_accept_term': 'Принять Положения и условия',
  'lbl_sign_up': 'Зарегистрироваться',
  'lbl_sign_in': 'Войти',
  'lbl_login': 'Войти в аккаунт',
  'lbl_logout': 'Выход',
  'lbl_ok': 'OK',
  'lbl_submit': 'Отправить',
  'lbl_save': 'Сохранить',
  'lbl_verify_email': 'Проверка электронной почты',
  'lbl_reset_password': 'Сброс пароля',
  'lbl_home': 'Главная',
  'lbl_my_profile': 'Личный кабинет',
  'lbl_language_selection': 'Выбор языка',
  'lbl_notification': 'Уведомления',
  'lbl_are_you_vaccinated': 'Вы вакцинированы?',
  'lbl_search_details': 'Критерии поиска',
  'lbl_travel_rules_from': 'Правила въезда из',
  'lbl_to': 'в',
  'lbl_required_test': 'Обязательный тест',
  'lbl_test_time': 'Время тестирования',
  'lbl_age_reqiured_test': 'Минимальный возраст для обязательного тестирования',
  'lbl_quarantine_required': 'Обязательный карантин',
  'lbl_additional_doc_required':
      'Обязательный(ые) дополнительный(ые) документ(ы)',
  'lbl_link_submit_doc': 'Ссылка для отправки документа',
  'lbl_more_info_about_result':
      'Дополнительная информация о требованиях к въезду',
  'lbl_test_required_for_country': 'Тест, необходимый для',
  'lbl_session_expired': 'Сессия истекла',
  'lbl_logout_msg': 'Выйти из системы?',
  'lbl_cancel': 'Отмена',
  'lbl_yes': 'Да',
  'lbl_no': 'Нет',
  'lbl_days': 'Дни',
  'lbl_day': 'День',
  'lbl_year': 'Год',
  'lbl_years': 'Годы',
  'lbl_session_expired_msg':
      'Из-за входа в систему на другом устройстве сессия была завершена.',
  'lbl_within_last': 'Не позднее чем за',
  'lbl_hours_of_departure': 'часа(ов) до отправления',
  'lbl_pfl_required':
      'Необходимо предварительная отправка сведений о пассажирах',
  'lbl_pfl_not_required':
      'Предварительная отправка сведений о пассажирах не требуется',
  'lbl_before_arrival_in': 'До прибытия в',
  'lbl_on_arrival_in': 'По прибытии в',
  'lbl_select_image': 'Выберите изображение',
  'lbl_camera': 'Камера',
  'lbl_gallery': 'Галерея',
  'lbl_update_app': 'Обновить приложение',
  'lbl_not_now': 'Не сейчас',
  'msg_something_went_wrong': 'Возникла ошибка.',
  'msg_new_update': 'Доступно новое обновление.',
  'msg_force_update': 'Необходимо принудительно обновить приложение',
  'msg_check_connection': 'Проверьте подключение к Интернету.',
  'msg_enter_full_name': 'Введите ФИО',
  'msg_name_length': 'Имя должно содержать не более 70 символов',
  'msg_enter_email': 'Введите электронную почту',
  'msg_enter_valid_email': 'Введите действительный адрес электронной почты',
  'msg_enter_phone_number': 'Введите номер телефона',
  'msg_enter_valid_phone_number': 'Введите действительный номер телефона',
  'msg_phone_number_limit': 'Количество символов должно быть не менее 8',
  'msg_phone_number_max_limit': 'Количество символов должно быть не более 15',
  'msg_enter_password': 'Введите пароль',
  'msg_enter_old_password': 'Введите старый пароль',
  'msg_enter_new_password': 'Введите новый пароль',
  'msg_enter_confirm_password': 'Подтвердите пароль',
  'msg_password_limit': 'Пароль должен содержать не менее 8 символов',
  'msg_password_max_limit': 'Пароль должен содержать не более 15 символов',
  'msg_new_password_limit': 'Новый пароль должен содержать не менее 8 символов',
  'msg_confirm_password_limit':
      'Пароль для подтверждения должен содержать не менее 8 символов',
  'msg_password_not_match':
      'Пароль и пароль для подтверждения должны совпадать',
  'msg_new_password_not_match':
      'Новый пароль и пароль для подтверждения должны совпадать',
  'msg_country_select': 'Выберите страну',
  'msg_select_profile_photo': 'Выберите фотографию профиля',
  'msg_enter_traveling_from': 'Укажите страну отправления',
  'msg_enter_traveling_to': 'Укажите страну назначения',
  'msg_same_country': 'Путешествие из и путешествие в страны не могут быть одинаковыми',
  'msg_no_data_found': 'Данные не найдены',
  'msg_accept_terms_condition': 'Пожалуйста, примите условия',
  'msg_select_dob': 'Выберите дату рождения',
  'msg_select_country': 'Выберите страну',
  'lbl_alert': 'КЛИКНИТЕ СЮДА',
  'lbl_more_information': 'Эта страна имеет больше туристической информации',
  'lbl_click_here': 'КЛИКНИТЕ СЮДА',
  'lbl_none': 'Никто',
  'lbl_not_required': 'Не требуется',
  'lbl_home_content':
      'Полностью вакцинирован"" означает, что вы получили полную дозу одобренной вакцины.'
          '\n\nНапример, 2 дозы Pfizer BioNTech, 2 дозы Moderna, 1 дозу Janssen.'
          '\nВы считаетесь полностью вакцинированным через 2 недели после получения последней дозы. Если вы были частично вакцинированы или путешествуете в течение 2 недель после получения последней дозы, вы считаетесь не вакцинированным.',
  'lbl_share_app': 'Поделитесь ссылкой на Бербе',
  'lbl_share': 'Делиться',
  'lbl_share_content': 'Ознакомьтесь с последними правилами въезда из страны в страну с помощью Berbe. Это быстро, просто, точно и совершенно бесплатно. Загрузите его на https://berbe.net. Berbe делает путешествия проще!',
  'lbl_accept': 'Accept ',
  'lbl_terms_condition': 'Terms & Conditions',
  'msg_verify_email':
  'We have sent an activation link to your email. Please activate your account to Sign in. If you do not receive a confirmation email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
  'msg_reset_password':
  'We have sent an reset password link to your email. If you do not receive an email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
};
