const Map<String, String> stSpanish = {
  'hint_enter_email': 'ID de correo electrónico',
  'hint_password': 'Contraseña',
  'hint_old_password': 'Antigua Contraseña',
  'hint_new_password': 'Nueva Contraseña',
  'hint_confirm_password': 'Confirmar Contraseña',
  'hint_full_name': 'Nombre Completo*',
  'hint_dob': 'Fecha de Nacimiento*',
  'hint_phone_number': 'Número de teléfono*',
  'hint_country_selection': 'Selección de País*',
  'hint_traveling_from': '¿País de oriden del viaje?',
  'hint_traveling_to': '¿País destino del viaje?',
  'lbl_forgot_password': '¿Has olvidado tu contraseña?',
  'lbl_forgot_password_title': 'Has olvidado tu contraseña',
  'lbl_change_password': 'Cambiar contraseña',
  'lbl_delete_account': 'Borrar cuenta',
  'lbl_dont_have_account': '¿No tienes una cuenta? ',
  'lbl_already_have_account': '¿Ya tienes una cuenta? ',
  'lbl_accept_term': 'Aceptar Términos y Condiciones',
  'lbl_sign_up': 'Regístrate',
  'lbl_sign_in': 'Acceder',
  'lbl_login': 'Iniciar sesión',
  'lbl_logout': 'Cerrar sesión',
  'lbl_ok': 'Vale',
  'lbl_submit': 'Enviar',
  'lbl_save': 'Guardar',
  'lbl_verify_email': 'Verificar correo electrónico',
  'lbl_reset_password': 'Restablecer la contraseña',
  'lbl_home': 'Inicio',
  'lbl_my_profile': 'Mi Perfil',
  'lbl_language_selection': 'Selección de Idioma',
  'lbl_notification': 'Notificación',
  'lbl_are_you_vaccinated': '¿Estás Vacunado?',
  'lbl_search_details': 'Detalles de Búsqueda',
  'lbl_travel_rules_from': 'Normas de Viaje de',
  'lbl_to': 'a',
  'lbl_required_test': 'Test Requerido',
  'lbl_test_time': 'Tiempo de la Prueba',
  'lbl_age_reqiured_test': 'Edad Mínima Requerida para el Test',
  'lbl_quarantine_required': 'Cuarentena Necesaria',
  'lbl_additional_doc_required': 'Documento(s) Adicional Requerido',
  'lbl_link_submit_doc': 'Enlace para enviar el documento',
  'lbl_more_info_about_result':
      'Más información sobre los requisitos de acceso',
  'lbl_test_required_for_country': 'Test Necesario Para',
  'lbl_session_expired': 'Sesión Expirada',
  'lbl_logout_msg': '¿Está seguro de que quiere cerrar la sesión?',
  'lbl_cancel': 'Cancelar',
  'lbl_yes': 'Sí',
  'lbl_no': 'No',
  'lbl_days': 'Días',
  'lbl_day': 'Día',
  'lbl_year': 'Año',
  'lbl_years': 'Años',
  'lbl_session_expired_msg':
      'La sesión ha expirado debido a que se inició sesión en otro dispositivo.',
  'lbl_within_last': 'Dentro de la última',
  'lbl_hours_of_departure': 'Horas de salida',
  'lbl_pfl_required': 'Se requiere información anticipada del pasajero',
  'lbl_pfl_not_required': 'No se requiere información anticipada del pasajero',
  'lbl_before_arrival_in': 'Antes de la llegada a',
  'lbl_on_arrival_in': 'Al llegar a',
  'lbl_select_image': 'Seleccionar imagen',
  'lbl_camera': 'Cámara',
  'lbl_gallery': 'Galería',
  'lbl_update_app': 'Actualizar aplicación',
  'lbl_not_now': 'Ahora no',
  'msg_something_went_wrong': 'Algo salió mal.',
  'msg_new_update': 'La nueva actualización ya está disponible.',
  'msg_force_update': 'Se necesita forzar la actualización de la aplicación',
  'msg_check_connection': 'Compruebe su conexión a internet.',
  'msg_enter_full_name': 'Por favor, introduzca su nombre completo',
  'msg_name_length': 'El nombre no debe tener más de 70 caracteres',
  'msg_enter_email': 'Por favor, introduzca su correo electrónico',
  'msg_enter_valid_email': 'Por favor, introduzca un correo electrónico válido',
  'msg_enter_phone_number': 'Por favor, introduzca un número de teléfono',
  'msg_enter_valid_phone_number':
      'Por favor, introduzca un número de teléfono válido',
  'msg_phone_number_limit': 'Se requiere un mínimo de 8 dígitos',
  'msg_phone_number_max_limit': 'Se requiere un máximo de 15 dígitos',
  'msg_enter_password': 'Por favor, introduzca la contraseña',
  'msg_enter_old_password': 'Por favor, introduzca su antigua contraseña',
  'msg_enter_new_password': 'Por favor, introduzca una nueva contraseña',
  'msg_enter_confirm_password':
      'Por favor, introduzca la contraseña de confirmación',
  'msg_password_limit': 'La contraseña debe de tener al menos 8 caracteres',
  'msg_password_max_limit':
      'La contraseña debe tener un máximo de 15 caracteres',
  'msg_new_password_limit':
      'La nueva contraseña debe tener al menos 8 caracteres',
  'msg_confirm_password_limit':
      'La contraseña de confirmación debe tener al menos 8 caracteres',
  'msg_password_not_match':
      'La contraseña y la contraseña de confirmación deben ser las mismas',
  'msg_new_password_not_match':
      'La contraseña nueva y la contraseña de confirmación deben ser las mismas',
  'msg_country_select': 'Seleccione el país',
  'msg_select_profile_photo': 'Seleccione la foto de perfil',
  'msg_enter_traveling_from': 'Introduzca el viaje desde',
  'msg_enter_traveling_to': 'Introduzca viajar a',
  'msg_same_country': 'Los países que viajan desde y hacia los que viajan no pueden ser iguales',
  'msg_no_data_found': 'No se han Encontrado Datos',
  'msg_accept_terms_condition': 'Por favor, acepte los términos y condiciones.',
  'msg_select_dob': 'Seleccionar fecha de nacimiento',
  'msg_select_country': 'Seleccionar país',
  'lbl_alert': 'ALERTA',
  'lbl_more_information': 'Este país tiene más información de viaje',
  'lbl_click_here': 'HAGA CLIC AQUÍ',
  'lbl_none': 'Ninguno',
  'lbl_not_required': 'No requerido',
  'lbl_home_content':
      'Completamente vacunado se refiere a que ha recibido la dosis completa de una vacuna aceptada.'
          '\n\nPor ejemplo Pfizer BioNTech = 2 dosis, Moderna = 2 dosis, Janssen = 1 dosis.'
          '\nSe le considera Completamente Vacunado una vez hayan pasado 2 semanas desde su última dosis. Si usted ha sido parcialmente vacunado o va a viajar durante las 2 semanas posteriores a su última dosis, se le considera No Vacunado.',
  'lbl_share_app': 'Compartir Berbé',
  'lbl_share': 'Cuota',
  'lbl_share_content': 'Consulta las últimas normativas de viaje de país a país con Berbe. Es rápido, sencillo, preciso y completamente gratuito. ¡Consíguelo en https://berbe.net Berbe, ¡haciendo que viajar sea sencillo!',
  'lbl_accept': 'Accept ',
  'lbl_terms_condition': 'Terms & Conditions',
  'msg_verify_email':
  'We have sent an activation link to your email. Please activate your account to Sign in. If you do not receive a confirmation email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
  'msg_reset_password':
  'We have sent an reset password link to your email. If you do not receive an email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
};
