const Map<String, String> stThai = {
  'hint_enter_email': 'อีเมล',
  'hint_password': 'รหัสผ่าน',
  'hint_old_password': 'รหัสผ่านเก่า',
  'hint_new_password': 'รหัสผ่านใหม่',
  'hint_confirm_password': 'รหัสผ่านยืนยัน',
  'hint_full_name': 'ชื่อ-นามสกุล*',
  'hint_dob': 'วันเดือนปีเกิด*',
  'hint_phone_number': 'หมายเลขโทรศัพท์*',
  'hint_country_selection': 'โปรดเลือกประเทศ*',
  'hint_traveling_from': 'ประเทศที่เดินทางมาจาก?',
  'hint_traveling_to': 'ประเทศที่จะเดินทางไป?',
  'lbl_forgot_password': 'ลืมรหัสผ่าน?',
  'lbl_forgot_password_title': 'ลืมรหัสผ่าน',
  'lbl_change_password': 'เปลี่ยนรหัสผ่าน',
  'lbl_delete_account': 'ลบบัญชี',
  'lbl_dont_have_account': 'ไม่มีบัญชีใช่ไหม? ',
  'lbl_already_have_account': 'มีบัญชีอยู่แล้วใช่ไหม? ',
  'lbl_accept_term': 'ยอมรับข้อกำหนดและเงื่อนไข',
  'lbl_sign_up': 'ลงทะเบียน',
  'lbl_sign_in': 'ลงชื่อเข้าใช้งาน',
  'lbl_login': 'เข้าสู่ระบบ',
  'lbl_logout': 'ออกจากระบบ',
  'lbl_ok': 'ตกลง',
  'lbl_submit': 'ยืนยัน',
  'lbl_save': 'บันทึก',
  'lbl_verify_email': 'ยืนยันอีเมล',
  'lbl_reset_password': 'รีเซ็ตรหัสผ่าน',
  'lbl_home': 'หน้าหลัก',
  'lbl_my_profile': 'ประวัติของฉัน',
  'lbl_language_selection': 'โปรดเลือกภาษา',
  'lbl_notification': 'การแจ้งเตือน',
  'lbl_are_you_vaccinated': 'คุณได้รับการฉีดวัคซีนหรือไม่?',
  'lbl_search_details': 'ค้นหารายละเอียด',
  'lbl_travel_rules_from': 'กฎระเบียบในการเดินทางจาก',
  'lbl_to': 'ไปยัง',
  'lbl_required_test': 'การทดสอบที่จำเป็น',
  'lbl_test_time': 'เวลาของการทดสอบ',
  'lbl_age_reqiured_test': 'อายุขั้นต่ำที่จำเป็นสำหรับการทดสอบ',
  'lbl_quarantine_required': 'ความจำเป็นในการกักตัว',
  'lbl_additional_doc_required': 'เอกสารเพิ่มเติมที่จำเป็น',
  'lbl_link_submit_doc': 'ลิงก์เพื่อส่งเอกสาร',
  'lbl_more_info_about_result':
      'ข้อมูลเพิ่มเติมเกี่ยวกับข้อกำหนดในการเข้าประเทศ',
  'lbl_test_required_for_country': 'การทดสอบที่จำเป็นสำหรับ',
  'lbl_session_expired': 'เซสชันหมดอายุแล้ว',
  'lbl_logout_msg': 'คุณแน่ใจหรือไม่ว่าคุณต้องการจะออกจากระบบ?',
  'lbl_cancel': 'ยกเลิก',
  'lbl_yes': 'ใช่',
  'lbl_no': 'ไม่',
  'lbl_days': 'วัน',
  'lbl_day': 'วัน',
  'lbl_year': 'ปี',
  'lbl_years': 'ปี',
  'lbl_session_expired_msg':
      'เซสชันหมดอายุแล้วเนื่องจากมีการลงชื่อเข้าใช้งานในอุปกรณ์อื่น',
  'lbl_within_last': 'ภายใน',
  'lbl_hours_of_departure': 'ชั่วโมงสุดท้ายก่อนออกเดินทาง',
  'lbl_pfl_required': 'จำเป็นต้องมีข้อมูลของผู้โดยสารล่วงหน้า',
  'lbl_pfl_not_required': 'ไม่จำเป็นต้องมีข้อมูลของผู้โดยสารล่วงหน้า',
  'lbl_before_arrival_in': 'ก่อนเดินทางมาถึง',
  'lbl_on_arrival_in': 'เมื่อเดินทางมาถึง',
  'lbl_select_image': 'เลือกรูปภาพ',
  'lbl_camera': 'กล้อง',
  'lbl_gallery': 'แกลลอรี่',
  'lbl_update_app': 'อัปเดตแอป',
  'lbl_not_now': 'ไม่ใช่ตอนนี้',
  'msg_something_went_wrong': 'มีบางอย่างผิดปกติ',
  'msg_new_update': 'มีการอัปเดตใหม่ในขณะนี้',
  'msg_force_update': 'จำเป็นต้องอัปเดตแอป',
  'msg_check_connection': 'ตรวจสอบการเชื่อมต่ออินเทอร์เน็ตของคุณ',
  'msg_enter_full_name': 'โปรดป้อนชื่อ-นามสกุล',
  'msg_name_length': 'ชื่อต้องมีความยาวไม่เกินกว่า 70 ตัวอักษร',
  'msg_enter_email': 'โปรดป้อนอีเมล',
  'msg_enter_valid_email': 'โปรดป้อนอีเมลที่ถูกต้อง',
  'msg_enter_phone_number': 'โปรดป้อนหมายเลขโทรศัพท์',
  'msg_enter_valid_phone_number': 'โปรดป้อนหมายเลขโทรศัพท์ที่ถูกต้อง',
  'msg_phone_number_limit': 'ต้องมีตัวเลขไม่ต่ำกว่า 8 หลัก',
  'msg_phone_number_max_limit': 'ต้องมีตัวเลขไม่เกินกว่า 15 หลัก',
  'msg_enter_password': 'โปรดป้อนรหัสผ่าน',
  'msg_enter_old_password': 'โปรดป้อนรหัสผ่านเก่า',
  'msg_enter_new_password': 'โปรดป้อนรหัสผ่านใหม่',
  'msg_enter_confirm_password': 'โปรดป้อนรหัสผ่านยืนยัน',
  'msg_password_limit': 'รหัสผ่านต้องมีความยาวไม่ต่ำกว่า 8 ตัวอักษร',
  'msg_password_max_limit': 'รหัสผ่านต้องมีความยาวไม่เกินกว่า 15 ตัวอักษร',
  'msg_new_password_limit': 'รหัสผ่านใหม่ต้องมีความยาวไม่ต่ำกว่า 8 ตัวอักษร',
  'msg_confirm_password_limit':
      'รหัสผ่านยืนยันต้องมีความยาวไม่ต่ำกว่า 8 ตัวอักษร',
  'msg_password_not_match': 'รหัสผ่านและยืนยันรหัสผ่านต้องเหมือนกัน',
  'msg_new_password_not_match': 'รหัสผ่านใหม่และรหัสผ่านยืนยันต้องเหมือนกัน',
  'msg_country_select': 'โปรดเลือกประเทศ',
  'msg_select_profile_photo': 'โปรดเลือกรูปโปรไฟล์',
  'msg_enter_traveling_from': 'โปรดป้อน เดินทางจาก',
  'msg_enter_traveling_to': 'โปรดป้อน เดินทางไปยัง',
  'msg_same_country': 'การเดินทางจากและการเดินทางไปยังประเทศต่างๆ จะเหมือนกันไม่ได้',
  'msg_no_data_found': 'ไม่พบข้อมูล',
  'msg_accept_terms_condition': 'โปรดยอมรับข้อกำหนดและเงื่อนไข',
  'msg_select_dob': 'เลือกวันเดือนปีเกิด',
  'msg_select_country': 'เลือกประเทศ',
  'lbl_alert': 'เตือน',
  'lbl_more_information': 'ประเทศนี้มีข้อมูลการเดินทางเพิ่มเติม',
  'lbl_click_here': 'คลิกที่นี่',
  'lbl_none': 'ไม่มี',
  'lbl_not_required': 'ไม่ต้องการ',
  'lbl_home_content':
      'การฉีดวัคซีนครบถ้วนแล้ว หมายความว่าคุณได้รับวัคซีนที่ผ่านการรับรองเต็มโดสแล้ว'
          '\n\nยกตัวอย่างเช่น Pfizer BioNTech = 2 โดส Moderna = 2 โดส Janssen = 1 โดส'
          '\nคุณจะถือว่าเป็นผู้ที่ได้ฉีดวัคซีนครบถ้วนหลังจากผ่านวันที่ได้รับโดสสุดท้ายไปแล้วเป็นเวลา 2 สัปดาห์ ถ้าคุณได้รับการฉีดวัคซีนเพียงบางส่วน หรือเดินทางภายในระยะเวลา 2 สัปดาห์หลังจากที่ได้รับวัคซีนโดสสุดท้าย คุณจะถูกถือเป็นผู้ที่ยังไม่ได้รับการฉีดวัคซีน',
  'lbl_share_app': 'แบ่งปัน Berbe',
  'lbl_share': 'แบ่งปัน',
  'lbl_share_content': 'เปิดดูกฎการเดินทางล่าสุดจากประเทศหนึ่งไปอีกประเทศหนึ่งได้ด้วย Berbe ทั้งรวดเร็ว เรียบง่าย แม่นยำ และก็ฟรี 100% อีกด้วย รับเลยที่ https://berbe.net Berbe ทำให้การเดินทางเป็นเรื่องง่าย!',
  'lbl_accept': 'Accept ',
  'lbl_terms_condition': 'Terms & Conditions',
  'msg_verify_email':
  'We have sent an activation link to your email. Please activate your account to Sign in. If you do not receive a confirmation email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
  'msg_reset_password':
  'We have sent an reset password link to your email. If you do not receive an email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
};
