const Map<String, String> stTurkish = {
  'hint_enter_email': 'E-posta',
  'hint_password': 'Şifre',
  'hint_old_password': 'Eski Şifre',
  'hint_new_password': 'Yeni Şifre',
  'hint_confirm_password': 'Şifreyi Doğrula',
  'hint_full_name': 'İsim-Soyisim*',
  'hint_dob': 'Doğum Tarihi*',
  'hint_phone_number': 'Telefon Numarası*',
  'hint_country_selection': 'Ülke Seçimi*',
  'hint_traveling_from': 'Hangi ülkeden seyahat edeceksiniz?',
  'hint_traveling_to': 'Hangi ülkeye seyahat edeceksiniz?',
  'lbl_forgot_password': 'Şifrenizi mi unuttunuz?',
  'lbl_forgot_password_title': 'Şifrenizi mi unuttunuz',
  'lbl_change_password': 'Şifre değiştir',
  'lbl_delete_account': 'Hesabı sil',
  'lbl_dont_have_account': 'Hesabınız yok mu? ',
  'lbl_already_have_account': 'Zaten bir hesabınız var mı? ',
  'lbl_accept_term': 'Hüküm ve Şartları Kabul Et',
  'lbl_sign_up': 'Kaydol',
  'lbl_sign_in': 'Giriş Yap',
  'lbl_login': 'Oturum Aç',
  'lbl_logout': 'Oturumu Kapat',
  'lbl_ok': 'Tamam',
  'lbl_submit': 'Yükle',
  'lbl_save': 'Kaydet',
  'lbl_verify_email': 'E-posta Doğrula',
  'lbl_reset_password': 'Şifreyi yenile',
  'lbl_home': 'Anasayfa',
  'lbl_my_profile': 'Profilim',
  'lbl_language_selection': 'Dil Seçimi',
  'lbl_notification': 'Bildirim',
  'lbl_are_you_vaccinated': 'Aşılarınızı Yaptırdınız Mı?',
  'lbl_search_details': 'Arama Bilgileri',
  'lbl_travel_rules_from': 'Seyahat Kuralları - Nereden:',
  'lbl_to': 'Nereye:',
  'lbl_required_test': 'Gerekli Testler',
  'lbl_test_time': 'Test Saati',
  'lbl_age_reqiured_test': 'Test Yaptırması Gereken En Düşük Yaş',
  'lbl_quarantine_required': 'Karantina gerekiyor mu?',
  'lbl_additional_doc_required': 'Ek belge gerekiyor mu?',
  'lbl_link_submit_doc': 'Belge yükleme bağlantısı',
  'lbl_more_info_about_result':
      'Ülkeye giriş gereklilikleri ilgili daha fazla bilgi için',
  'lbl_test_required_for_country': 'Gerekli Testler',
  'lbl_session_expired': 'Oturum Sona Erdi',
  'lbl_logout_msg': 'Oturumu kapatmak istediğinize emin misiniz?',
  'lbl_cancel': 'İptal',
  'lbl_yes': 'Evet',
  'lbl_no': 'Hayır',
  'lbl_days': 'Gün',
  'lbl_day': 'Gün',
  'lbl_year': 'Yıl',
  'lbl_years': 'Yıl',
  'lbl_session_expired_msg':
      'Başka bir cihazda giriş yapıldığı için oturum sona erdi.',
  'lbl_within_last': 'Kalkış saatinden önce',
  'lbl_hours_of_departure': 'saat içerisinde',
  'lbl_pfl_required': 'Özel güvenlik bilgileri gerekiyor',
  'lbl_pfl_not_required': 'Özel güvenlik bilgileri gerekmiyor',
  'lbl_before_arrival_in': 'Seyahat Öncesi:',
  'lbl_on_arrival_in': 'Seyahat Sonrası:',
  'lbl_select_image': 'Fotoğraf seç',
  'lbl_camera': 'Kamera',
  'lbl_gallery': 'Galeri',
  'lbl_update_app': 'Uygulamayı Güncelle',
  'lbl_not_now': 'Şimdi değil',
  'msg_something_went_wrong': 'Bir şeyler ters gitti.',
  'msg_new_update': 'Yeni güncelleme mevcut.',
  'msg_force_update': 'Uygulamayı mecburen güncelleniz gerekiyor',
  'msg_check_connection': 'İnternet bağlantınızı kontrol edin.',
  'msg_enter_full_name': 'Lütfen isminizi ve soyisminizi girin',
  'msg_name_length': 'İsminiz 70 karakterden uzun olamaz',
  'msg_enter_email': 'Lütfen e-postanızı girin',
  'msg_enter_valid_email': 'Lütfen gerçerli bir e-posta girin',
  'msg_enter_phone_number': 'Lütfen telefon numaranızı girin',
  'msg_enter_valid_phone_number': 'Lütfen geçerli bir telefon numarası girin',
  'msg_phone_number_limit': 'En az 8 karakter olmalıdır',
  'msg_phone_number_max_limit': 'En fazla 15 karakter olmalıdır',
  'msg_enter_password': 'Lütfen şifrenizi girin',
  'msg_enter_old_password': 'Lütfen eski şifrenizi girin',
  'msg_enter_new_password': 'Lütfen yeni şifrenizi girin',
  'msg_enter_confirm_password': 'Lütfen şifrenizi tekrar girin',
  'msg_password_limit': 'Şifre en az 8 karakterden oluşmalıdır',
  'msg_password_max_limit': 'Şifre en fazla 15 karakter içermelidir',
  'msg_new_password_limit': 'Yeni şifre en az 8 karakterden oluşmalıdır',
  'msg_confirm_password_limit': 'Şifre doğrula en az 8 karakterden oluşmalıdır',
  'msg_password_not_match': 'Şifre ve onay şifresi aynı olmalıdır',
  'msg_new_password_not_match': 'Yeni şifre ve şifre doğrula aynı olmalıdır',
  'msg_country_select': 'Lütfen ülke seçin',
  'msg_select_profile_photo': 'Lütfen profil resmi seçin',
  'msg_enter_traveling_from': 'Lütfen nereden seyahat edeceğinizi seçiniz',
  'msg_enter_traveling_to': 'Lütfen nereye seyahat edeceğinizi seçiniz',
  'msg_same_country': 'Ülkelerden Seyahat ve Ülkelere Seyahat aynı olamaz',
  'msg_no_data_found': 'Veri Bulunamadı',
  'msg_accept_terms_condition': 'Lütfen şartlar ve koşulları kabul edin',
  'msg_select_dob': 'Doğum tarihini seçin',
  'msg_select_country': 'Ülke seçin',
  'lbl_alert': 'ALARM',
  'lbl_more_information': 'Bu ülkede daha fazla seyahat bilgisi var',
  'lbl_click_here': 'BURAYA TIKLAYIN',
  'lbl_none': 'Hiçbiri',
  'lbl_not_required': 'Hiçbiri',
  'lbl_home_content':
      'Tam aşılı demek, onaylanmış bir aşının tüm dozlarını olduğunuz anlamına gelir.'
          '\n\nÖrneğin; Pfizer BioNTech = 2 doz, Moderna = 2 doz, Janssen = 1 doz.'
          '\nSon aşı dozunuzdan 2 hafta sonra ""Tam Aşılı"" olarak sayılırsınız. Dozlarınız tam değilse veya son dozunuzdan sonraki 2 hafta içerisinde seyahat edecekseniz, ""Aşılı Değil"" olarak kabul edilirsiniz.',
  'lbl_share_app': 'Berbe tesisini paylaşın',
  'lbl_share': 'Paylaş',
  'lbl_share_content':
      'Berbe ile ülkeden ülkeye seyahat etmek için en güncel kurallara göz atın. Hızlı, basit, doğru ve tamamen ücretsiz. https://berbe.net adresinden uygulamaya erişin. Berbe, seyahati kolaylaştırıyor!',
  'lbl_accept': 'Accept ',
  'lbl_terms_condition': 'Terms & Conditions',
  'msg_verify_email':
      'We have sent an activation link to your email. Please activate your account to Sign in. If you do not receive a confirmation email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
  'msg_reset_password':
      'We have sent an reset password link to your email. If you do not receive an email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
};
