const Map<String, String> stUrdu = {
  'hint_enter_email': 'ای میل آئی ڈی',
  'hint_password': 'پاس ورڈ',
  'hint_old_password': 'پرانا پاسورڈ',
  'hint_new_password': 'نیا پاس ورڈ',
  'hint_confirm_password': 'پاس ورڈ کنفرم کیجئے',
  'hint_full_name': 'مکمل نام*',
  'hint_dob': 'تاریخِ پیدائش*',
  'hint_phone_number': 'فون نمبر*',
  'hint_country_selection': 'ملک کا انتخاب کیجئے *',
  'hint_traveling_from': 'ملک جس سے سفر کر رہے ہیں؟',
  'hint_traveling_to': 'ملک جس کی جانب سفر کر رہے ہیں؟',
  'lbl_forgot_password': 'پاسورڈ بھول گئے؟',
  'lbl_forgot_password_title': 'پاسورڈ بھول گئے',
  'lbl_change_password': 'پاس ورڈ تبدیل کیجئے',
  'lbl_delete_account': 'کھاتہ مٹا دو',
  'lbl_dont_have_account': 'اکاؤنٹ نہیں ہے؟ ',
  'lbl_already_have_account': 'پہلے سے ہی ایک اکاؤنٹ موجود ہے؟ ',
  'lbl_accept_term': 'شرائط و ضوابط قبول کیجئے',
  'lbl_sign_up': 'سائن اَپ',
  'lbl_sign_in': 'سائن اِن',
  'lbl_login': 'لاگ اِن',
  'lbl_logout': 'لاگ آوٹ',
  'lbl_ok': 'ٹھیک ہے',
  'lbl_submit': 'جمع کرائیں',
  'lbl_save': 'محفوظ کریں',
  'lbl_verify_email': 'ای میل کی توثیق کریں',
  'lbl_reset_password': 'پاس ورڈ ری سیٹ',
  'lbl_home': 'ہوم',
  'lbl_my_profile': 'میرا پروفائل',
  'lbl_language_selection': 'زبان کا انتخاب',
  'lbl_notification': 'نوٹیفیکیشن',
  'lbl_are_you_vaccinated': 'کیا آپکی ویکسین ہوچکی ہے؟',
  'lbl_search_details': 'تلاش کی تفصیلات',
  'lbl_travel_rules_from': 'سفر کے قوانین منجانب',
  'lbl_to': 'بجانب',
  'lbl_required_test': 'درکار ٹیسٹ',
  'lbl_test_time': 'ٹیسٹ کا وقت',
  'lbl_age_reqiured_test': 'امتحان کے لئے کم از کم درکار عمر',
  'lbl_quarantine_required': 'قرنطینہ کرنے کی ضرورت ہے',
  'lbl_additional_doc_required': 'اضافی دستاویزات کی ضرورت ہے',
  'lbl_link_submit_doc': 'دستاویز جمع کرنے کے لئے لنک',
  'lbl_more_info_about_result': 'انٹری کی ضروریات کے بارے میں مزید معلومات',
  'lbl_test_required_for_country': 'کے لئے ٹیسٹ ضروری ہے',
  'lbl_session_expired': 'سیشن ختم ہوگیا',
  'lbl_logout_msg': 'کیا آپ کو یقین ہے کہ آپ لاگ آؤٹ کرنا چاہتے ہیں؟',
  'lbl_cancel': 'منسوخ',
  'lbl_yes': 'جی ہاں',
  'lbl_no': 'نہیں',
  'lbl_days': 'دنوں',
  'lbl_day': 'دن',
  'lbl_year': 'سال',
  'lbl_years': 'سالوں',
  'lbl_session_expired_msg':
      'کسی دوسری ڈیوائس پر لاگ ان ہونے کی وجہ سے سیشن ختم ہوگیا۔',
  'lbl_within_last': 'آخری کے اندر اندر',
  'lbl_hours_of_departure': 'روانگی کے گھنٹے',
  'lbl_pfl_required': 'مسافر کی معلومات کی پیشگی ضرورت ہے',
  'lbl_pfl_not_required': 'مسافر کی معلومات کی پیشگی ضرورت نہیں ہے',
  'lbl_before_arrival_in': 'آمد سے پہلے',
  'lbl_on_arrival_in': 'آمد پر',
  'lbl_select_image': 'تصویر منتخب کریں۔',
  'lbl_camera': 'کیمرہ',
  'lbl_gallery': 'گیلری',
  'lbl_update_app': 'ایپ کو اپ ڈیٹ کریں۔',
  'lbl_not_now': 'ابھی نہیں',
  'msg_something_went_wrong': 'کچھ غلط ہو گیا ہے۔',
  'msg_new_update': 'اب نئی اپ ڈیٹ دستیاب ہے۔',
  'msg_force_update': 'ایپ کو لازمی اپ ڈیٹ کرنے کی ضرورت ہے',
  'msg_check_connection': 'اپنا انٹرنیٹ کنکشن چیک کیجئے۔',
  'msg_enter_full_name': 'براہ مہربانی مکمل نام درج کریں',
  'msg_name_length': 'نام 70 حروف سے زیادہ نہیں ہونا چاہئے',
  'msg_enter_email': 'براہ مہربانی ای میل درج کریں',
  'msg_enter_valid_email': 'برائے مہربانی درست ای میل درج کریں',
  'msg_enter_phone_number': 'برائے مہربانی فون نمبر درج کریں',
  'msg_enter_valid_phone_number': 'برائے مہربانی درست فون نمبر درج کریں',
  'msg_phone_number_limit': 'کم سے کم 8 حروف درکار ہیں',
  'msg_phone_number_max_limit': 'زیادہ سے زیادہ 15 حروف ہوسکتے ہیں',
  'msg_enter_password': 'برائے مہربانی پاس ورڈ درج کریں',
  'msg_enter_old_password': 'برائے مہربانی پرانا پاس ورڈ درج کریں',
  'msg_enter_new_password': 'برائے مہربانی نیا پاس ورڈ درج کریں',
  'msg_enter_confirm_password': 'برائے مہربانی پاس ورڈ کی تصدیق کریں',
  'msg_password_limit': 'پاس ورڈ کم از کم 8 حروف کا ہونا ضروری ہے',
  'msg_password_max_limit': 'پاس ورڈ زیادہ سے زیادہ 15 حروف کا ہوسکتا ہے',
  'msg_new_password_limit': 'نیا پاس ورڈ کم از کم 8 حروف کا ہونا ضروری ہے',
  'msg_confirm_password_limit':
      'پاس ورڈ کنفرم کریں، کم سے کم 8 حروف ہونا ضروری ہیں',
  'msg_password_not_match': 'پاس ورڈ اور کنفرم پاس ورڈ ایک جیسا ہونا چاہیے۔',
  'msg_new_password_not_match':
      'نیا پاس ورڈ اور کنفرم کیا گیا پاس ورڈ ایک جیسا ہونا ضروری ہے',
  'msg_country_select': 'برائے مہربانی ملک کا انتخاب کریں',
  'msg_select_profile_photo': 'برائے مہربانی پروفائل تصویر منتخب کریں',
  'msg_enter_traveling_from': 'جس جگہ کی جانب سفر کر رہے وہ درج کریں',
  'msg_enter_traveling_to': 'جس جگہ سے سفر کر رہے وہ درج کریں',
  'msg_same_country': 'ممالک سے سفر کرنا اور سفر کرنا ایک جیسا نہیں ہو سکتا',
  'msg_no_data_found': 'کوئی ڈیٹا نہیں ملا',
  'msg_accept_terms_condition': 'براہ کرم شرائط و ضوابط کو قبول کریں۔',
  'msg_select_dob': 'تاریخ پیدائش منتخب کریں۔',
  'msg_select_country': 'ملک کا انتخاب کیجئے',
  'lbl_alert': 'الرٹ',
  'lbl_more_information': 'اس ملک میں سفری معلومات زیادہ ہیں۔',
  'lbl_click_here': 'یہاں کلک کریں',
  'lbl_none': 'کوئی نہیں۔',
  'lbl_not_required': 'ضرورت نہیں ہے',
  'lbl_home_content':
      ' مکمل ویکسین شدہ سے مراد یہ ہے کہ آپ نے منظور شدہ ویکسین کی مکمل خوراک وصول کر لی ہے۔'
          '\n\nمثلاً فائزر بائیون ٹیک = 2 خوراکیں، موڈرنا = 2 خوراکیں، جانسن = 1 خوراک۔'
          '\nآپ کو اپنی آخری خوراک لینے کے 2 ہفتوں بعد مکمل ویکسین شدہ تصور کیا جاتا ہے۔ اگر آپ جزوی طور پر ویکسین شدہ ہوں، یا اپنی آخری خوراک لیے جانے کے بعد 2 ہفتوں کے اندر سفر کر رہے ہوں تو، آپ کو غیر ویکسین شدہ تصور کیا جاتا ہے۔',
  'lbl_share_app': 'بربی کو شیئر کریں۔',
  'lbl_share': 'بانٹیں',
  'lbl_share_content': 'ایپ Berbe کے ذریعے ملک تا ملک تازہ ترین سفری ضوابط کی پڑتال کریں۔ یہ تیز، سادہ، صحیح اور مکمل طور پر مفت ہے۔ اسے https://berbe.net پر حاصل کریں Berbe، سفر کو آسان بناتی ہے!',
  'lbl_accept': 'Accept ',
  'lbl_terms_condition': 'Terms & Conditions',
  'msg_verify_email':
  'We have sent an activation link to your email. Please activate your account to Sign in. If you do not receive a confirmation email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
  'msg_reset_password':
  'We have sent an reset password link to your email. If you do not receive an email, please check your spam folder. If you still do not receive an email, please contact support at info@berbe.net .',
};
