name: berbe
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7+13

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
  cupertino_icons: ^1.0.2
  intl:
  #Utilities
  shared_preferences:
  connectivity:
  flutter_typeahead:
  device_info_plus: ^3.2.3
  #State management
  get:
  #Flutter Svg
  flutter_svg:
  #CachedNetwork
  cached_network_image:
  #ApiCall
  http:
  #Lottie
  lottie:
  #ImagePicker/Cropper
  #image_picker: ^0.8.4+2
  image_picker:
  image_cropper:
  #PrmissionHandler
  permission_handler:
  #PackageInfo
  package_info_plus:
  #LaunchToStore
  launch_review:
  #FirebaseMessaging
  firebase_analytics:
  firebase_core:
  firebase_messaging:
  flutter_local_notifications:
  #FirebaseAuth
  firebase_auth: ^3.3.17
  google_sign_in: ^5.3.0
  flutter_facebook_auth: 4.0.0
  twitter_login: 4.1.0-dev
  sign_in_with_apple: ^4.0.0
  crypto: ^3.0.2
  #URLLaunch
  url_launcher:
#  CountryCode
  country_code_picker:
#  ShareLink
  share_plus:
  country_codes: ^2.0.1
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
        - asset: fonts/NotoSans-Regular.ttf